### PR TITLE
Prefer doas over sudo (fix #576)

### LINKED ISSUE #576: Inclusion of doas. Usage of dnf distro-sync
**I want to suggest some general feature**
I would like to be able to use _doas_ instead of _sudo_. and _distro-sync_ instead of _upgrade_ when using DNF in Fedora.
I think a line saying something like "Using sudo", "Using doas" etc as soon as topgrade is ran would also be a good call.

**More information**
distro-sync/dsync is a safer form of upgrading packages with DNF on Fedora. Using _dnf upgrade_ some times causes problems with packages versions. I had many problems with that in the past and none when I started using _dnf distro-sync_.
doas is a OpenBSD replacement for sudo with simplified configuration and simpler usage. I use Jesse Smith (slicer69)' port

- https://github.com/slicer69/doas;
- https://dnf.readthedocs.io/en/latest/command_ref.html#distro-sync-command-label;
- https://dnf.readthedocs.io/en/latest/command_ref.html#upgrade-command;

Example of today trying to use dnf upgrade:
```
❯ doas dnf upgrade
Last metadata expiration check: 2:14:04 ago on Sat Dec  5 19:48:09 2020.
Dependencies resolved.

 Problem 1: package qt5-qtwebengine-freeworld-5.15.1-1.fc33.x86_64 requires qt5-qtbase(x86-64) = 5.15.1, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.2-2.fc33.x86_64 and qt5-qtbase-5.15.1-7.fc33.x86_64
  - cannot install both qt5-qtbase-5.15.1-5.fc33.x86_64 and qt5-qtbase-5.15.2-2.fc33.x86_64
  - cannot install the best update candidate for package qt5-qtwebengine-freeworld-5.15.1-1.fc33.x86_64
  - cannot install the best update candidate for package qt5-qtbase-5.15.1-7.fc33.x86_64
 Problem 2: package telegram-desktop-2.4.7-3.fc33.x86_64 requires libQt5Gui.so.5(Qt_5.15.1_PRIVATE_API)(64bit), but none of the providers can be installed
  - cannot install both qt5-qtbase-gui-5.15.2-2.fc33.x86_64 and qt5-qtbase-gui-5.15.1-7.fc33.x86_64
  - cannot install both qt5-qtbase-gui-5.15.1-5.fc33.x86_64 and qt5-qtbase-gui-5.15.2-2.fc33.x86_64
  - cannot install the best update candidate for package telegram-desktop-2.4.7-3.fc33.x86_64
  - cannot install the best update candidate for package qt5-qtbase-gui-5.15.1-7.fc33.x86_64
 Problem 3: package python3-pyqtchart-5.15.0-3.fc33.x86_64 requires libQt5Charts.so.5(Qt_5.15.1_PRIVATE_API)(64bit), but none of the providers can be installed
  - cannot install both qt5-qtcharts-5.15.2-2.fc33.x86_64 and qt5-qtcharts-5.15.1-1.fc33.x86_64
  - cannot install both qt5-qtcharts-5.15.1-1.fc33.x86_64 and qt5-qtcharts-5.15.2-2.fc33.x86_64
  - cannot install the best update candidate for package qt5-qtcharts-5.15.1-1.fc33.x86_64
  - cannot install the best update candidate for package python3-pyqtchart-5.15.0-3.fc33.x86_64
 Problem 4: problem with installed package telegram-desktop-2.4.7-3.fc33.x86_64
  - package telegram-desktop-2.4.7-3.fc33.x86_64 requires libQt5WaylandClient.so.5(Qt_5.15.1_PRIVATE_API)(64bit), but none of the providers can be installed
  - cannot install both qt5-qtwayland-5.15.2-2.fc33.x86_64 and qt5-qtwayland-5.15.1-1.fc33.x86_64
  - cannot install both qt5-qtwayland-5.15.1-1.fc33.x86_64 and qt5-qtwayland-5.15.2-2.fc33.x86_64
  - cannot install the best update candidate for package qt5-qtwayland-5.15.1-1.fc33.x86_64
 Problem 5: problem with installed package qt5-qtwebengine-freeworld-5.15.1-1.fc33.x86_64
  - package qt5-qtwebengine-freeworld-5.15.1-1.fc33.x86_64 requires qt5-qtwebengine(x86-64) = 5.15.1, but none of the providers can be installed
  - cannot install both qt5-qtwebengine-5.15.2-1.fc33.x86_64 and qt5-qtwebengine-5.15.1-1.fc33.x86_64
  - cannot install both qt5-qtwebengine-5.15.1-1.fc33.x86_64 and qt5-qtwebengine-5.15.2-1.fc33.x86_64
  - cannot install the best update candidate for package qt5-qtwebengine-5.15.1-1.fc33.x86_64
===================================================================================================================================================
 Package                                Architecture                  Version                                 Repository                      Size
===================================================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt5-qtbase                             x86_64                        5.15.1-5.fc33                           fedora                         3.4 M
 qt5-qtbase                             x86_64                        5.15.2-2.fc33                           updates                        3.4 M
 qt5-qtbase-gui                         x86_64                        5.15.1-5.fc33                           fedora                         6.0 M
 qt5-qtbase-gui                         x86_64                        5.15.2-2.fc33                           updates                        6.0 M
 qt5-qtcharts                           x86_64                        5.15.2-2.fc33                           updates                        646 k
 qt5-qtwayland                          x86_64                        5.15.2-2.fc33                           updates                        1.0 M
 qt5-qtwebengine                        x86_64                        5.15.2-1.fc33                           updates                         55 M

Transaction Summary
===================================================================================================================================================
Skip  7 Packages

Nothing to do.
Complete!
```
Today's example using dnf distro-sync:
```
❯ doas dnf distro-sync
Last metadata expiration check: 2:16:42 ago on Sat Dec  5 19:48:09 2020.
Dependencies resolved.
===================================================================================================================================================
 Package                                  Architecture                  Version                                Repository                     Size
===================================================================================================================================================
Downgrading:
 kf5-kdeclarative                         x86_64                        5.73.0-2.fc33                          fedora                        301 k
 kf5-kxmlgui                              x86_64                        5.73.0-2.fc33                          fedora                        675 k
 qt5-qtbase                               x86_64                        5.15.1-5.fc33                          fedora                        3.4 M
 qt5-qtbase-common                        noarch                        5.15.1-5.fc33                          fedora                         11 k
 qt5-qtbase-gui                           x86_64                        5.15.1-5.fc33                          fedora                        6.0 M

Transaction Summary
===================================================================================================================================================
Downgrade  5 Packages

Total download size: 10 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): kf5-kdeclarative-5.73.0-2.fc33.x86_64.rpm                                                                   790 kB/s | 301 kB     00:00    
(2/5): qt5-qtbase-common-5.15.1-5.fc33.noarch.rpm                                                                  501 kB/s |  11 kB     00:00    
(3/5): kf5-kxmlgui-5.73.0-2.fc33.x86_64.rpm                                                                        823 kB/s | 675 kB     00:00    
(4/5): qt5-qtbase-5.15.1-5.fc33.x86_64.rpm                                                                         1.0 MB/s | 3.4 MB     00:03    
(5/5): qt5-qtbase-gui-5.15.1-5.fc33.x86_64.rpm                                                                     1.3 MB/s | 6.0 MB     00:04    
---------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                              1.9 MB/s |  10 MB     00:05     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                           1/1 
  Downgrading      : qt5-qtbase-common-5.15.1-5.fc33.noarch                                                                                   1/10 
  Running scriptlet: qt5-qtbase-5.15.1-5.fc33.x86_64                                                                                          2/10 
  Downgrading      : qt5-qtbase-5.15.1-5.fc33.x86_64                                                                                          2/10 
  Running scriptlet: qt5-qtbase-5.15.1-5.fc33.x86_64                                                                                          2/10 
  Downgrading      : qt5-qtbase-gui-5.15.1-5.fc33.x86_64                                                                                      3/10 
  Downgrading      : kf5-kdeclarative-5.73.0-2.fc33.x86_64                                                                                    4/10 
  Downgrading      : kf5-kxmlgui-5.73.0-2.fc33.x86_64                                                                                         5/10 
  Cleanup          : kf5-kxmlgui-5.75.0-1.fc33.x86_64                                                                                         6/10 
  Cleanup          : kf5-kdeclarative-5.75.0-1.fc33.x86_64                                                                                    7/10 
  Cleanup          : qt5-qtbase-gui-5.15.1-7.fc33.x86_64                                                                                      8/10 
  Cleanup          : qt5-qtbase-5.15.1-7.fc33.x86_64                                                                                          9/10 
  Running scriptlet: qt5-qtbase-5.15.1-7.fc33.x86_64                                                                                          9/10 
  Cleanup          : qt5-qtbase-common-5.15.1-7.fc33.noarch                                                                                  10/10 
  Running scriptlet: qt5-qtbase-common-5.15.1-7.fc33.noarch                                                                                  10/10 
  Verifying        : kf5-kdeclarative-5.73.0-2.fc33.x86_64                                                                                    1/10 
  Verifying        : kf5-kdeclarative-5.75.0-1.fc33.x86_64                                                                                    2/10 
  Verifying        : kf5-kxmlgui-5.73.0-2.fc33.x86_64                                                                                         3/10 
  Verifying        : kf5-kxmlgui-5.75.0-1.fc33.x86_64                                                                                         4/10 
  Verifying        : qt5-qtbase-5.15.1-5.fc33.x86_64                                                                                          5/10 
  Verifying        : qt5-qtbase-5.15.1-7.fc33.x86_64                                                                                          6/10 
  Verifying        : qt5-qtbase-common-5.15.1-5.fc33.noarch                                                                                   7/10 
  Verifying        : qt5-qtbase-common-5.15.1-7.fc33.noarch                                                                                   8/10 
  Verifying        : qt5-qtbase-gui-5.15.1-5.fc33.x86_64                                                                                      9/10 
  Verifying        : qt5-qtbase-gui-5.15.1-7.fc33.x86_64                                                                                     10/10 

Downgraded:
  kf5-kdeclarative-5.73.0-2.fc33.x86_64  kf5-kxmlgui-5.73.0-2.fc33.x86_64  qt5-qtbase-5.15.1-5.fc33.x86_64  qt5-qtbase-common-5.15.1-5.fc33.noarch 
  qt5-qtbase-gui-5.15.1-5.fc33.x86_64   

Complete!
```

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@msmafra please test this change

**Comment by msmafra** [comment]
Also did not work it seems. It uses the current user, right? I know because my doas is set to not ask for my password.

```
❯ topgrade --version
Topgrade 6.0.2

❯ topgrade --cleanup --yes

―― 14:47:54 - System update ―――――――――――――――――――――――――――――――――――――――――――――
[sudo] senha para marcelo: 
Última verificação de data de vencimento de metadados: 1:05:44 atrás em dom 06 dez 2020 13:42:21.
Dependências resolvidas.

```

**Comment by msmafra** [comment]
Forgot to put in verbose mode:

```
❯ topgrade --verbose --cleanup --yes
 2020-12-06T19:01:16.485Z DEBUG topgrade::config > Configuration at /home/marcelo/.config/topgrade.toml
 2020-12-06T19:01:16.485Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, post_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None, brew: None, linux: None, git: None, windows: None, vagrant: None }
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Detected "/usr/bin/notify-send" as "notify-send"
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Version: 6.0.2
 2020-12-06T19:01:16.485Z DEBUG topgrade         > OS: x86_64-unknown-linux-gnu
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Args { inner: ["topgrade", "--verbose", "--cleanup", "--yes"] }
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Binary path: Ok("/home/marcelo/.cargo/bin/topgrade")
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Self Update: false
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Detected "/usr/bin/git" as "git"
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Detected "/usr/bin/sudo" as "sudo"
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Cannot find "powershell"
 2020-12-06T19:01:16.485Z DEBUG topgrade::runner > Step "System update"

―― 16:01:16 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Path "/usr/bin/rpm-ostree" doesn't exist
 2020-12-06T19:01:16.486Z DEBUG topgrade::utils  > Path "/usr/bin/dnf" exists
 2020-12-06T19:01:16.486Z DEBUG topgrade::executor > Running "/usr/bin/sudo" "/usr/bin/dnf" "upgrade" "-y"

```

**Comment by msmafra** [comment]
Forgot to put in verbose mode:

```
❯ topgrade --verbose --cleanup --yes
 2020-12-06T19:01:16.485Z DEBUG topgrade::config > Configuration at /home/marcelo/.config/topgrade.toml
 2020-12-06T19:01:16.485Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, post_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None, brew: None, linux: None, git: None, windows: None, vagrant: None }
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Detected "/usr/bin/notify-send" as "notify-send"
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Version: 6.0.2
 2020-12-06T19:01:16.485Z DEBUG topgrade         > OS: x86_64-unknown-linux-gnu
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Args { inner: ["topgrade", "--verbose", "--cleanup", "--yes"] }
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Binary path: Ok("/home/marcelo/.cargo/bin/topgrade")
 2020-12-06T19:01:16.485Z DEBUG topgrade         > Self Update: false
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Detected "/usr/bin/git" as "git"
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Detected "/usr/bin/sudo" as "sudo"
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Cannot find "powershell"
 2020-12-06T19:01:16.485Z DEBUG topgrade::runner > Step "System update"

―― 16:01:16 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-12-06T19:01:16.485Z DEBUG topgrade::utils  > Path "/usr/bin/rpm-ostree" doesn't exist
 2020-12-06T19:01:16.486Z DEBUG topgrade::utils  > Path "/usr/bin/dnf" exists
 2020-12-06T19:01:16.486Z DEBUG topgrade::executor > Running "/usr/bin/sudo" "/usr/bin/dnf" "upgrade" "-y"

```

**Comment by r-darwish** [comment]
See [this comment](https://github.com/r-darwish/topgrade/pull/579#issuecomment-739694909)

**Pull request merged**
