### PR TITLE
Bash-it (fix #621)

### LINKED ISSUE #621: Bash-it support
**I want to suggest some general feature**
Topgrade should support (please?) [bash-it](https://bash-it.readthedocs.io/en/latest/)

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@dsh1705 can you please test this change?

**Comment by dsh1705** [comment]
Works on Mac BigSur 11.2.1 - can the config file be modified to handle an option to point Bash-It to the "dev" branch, instead of stable?

**Comment by r-darwish** [comment]
I pushed another commit introducing a config variable named `bashit_branch` which defaults to `stable`

**Comment by dsh1705** [comment]
Added the following in my topgrade.toml:

`[bashit_branch]
  bashit_branch = "dev"`

but received this error:

`failed to load configuration: unknown field `bashit_branch`, expected one of `pre_commands`, `post_commands`, `commands`, `git_repos`, `predefined_git_repos`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `git_arguments`, `tmux_arguments`, `set_title`, `assume_yes`, `yay_arguments`, `no_retry`, `run_in_tmux`, `cleanup`, `notify_each_step`, `accept_all_windows_updates`, `only`, `composer`, `brew`, `linux`, `git`, `windows`, `vagrant` at line 82 column 1`

**Comment by dsh1705** [comment]
After realizing my initial mistake, it works! Awesome!

`Would you like to update to origin/master(2d56cc4)? [Y/n] y
Bash-it successfully updated.

Migrating your installation to the latest dev version now...

All done, enjoy!`

**Pull request merged**
