### PR TITLE
Do not run Conda if auto_activate_base is set to False (fix #840)

### LINKED ISSUE #840: 8.2.0 broke conda's `auto_activate_base: false`
I have the following line in my `.condarc` to not have an active base by default

```
auto_activate_base: false
```

**What did you expect to happen?**

When running topgrade I expect that it can either deal with it or does nothing.

**What actually happened?**

Instead topgrade shows

```
―― 14:33:32 - Conda ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.



Retry? (y)es/(N)o/(s)hell
```

**Additional details:**
- Fedora 35
- cargo

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
@bdaase  please test this change

**Comment by bdaase** [comment]
Is there any easy way to do so?

**Comment by r-darwish** [comment]
Clone this branch and run `cargo run -- --show-skipped`. You should see that Conda is skipped due to your configuration.

**Comment by bdaase** [comment]
```
conda: SKIPPED: auto_activate_base is set to False
```

Thanks, works as expected.

**Pull request merged**
