### PR TITLE
Fossil support

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@Dialga can you please test this change?

**Comment by Dialga** [comment]
It should be the other way around `all sync` so it runs `fossil all sync`.

**Comment by r-darwish** [comment]
> 
> 
> It should be the other way around `all sync` so it runs `fossil all sync`.

fixed

**Comment by Dialga** [comment]
I've just tested this, I can confirm it works great. :+1:

**Pull request merged**
