### PR TITLE
Fix composer output (fix #402)

### LINKED ISSUE #402: Composer is still not writing output to console
**What did you expect to happen?**
The output of `composer global update` should be shown in the console.

**What actually happened?**
The composer step never outputs anything.

**Additional details:**
I actually introduced this "bug" myself in #315 because I couldn't figure out how to examine the output of the command while still sending it to the console. If it's an easy fix, It would be awesome if you could re-enable it.

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
@mortenscheel can you please test?

**Comment by mortenscheel** [comment]
I'm still not getting any output, but I have a hunch what the issue might be. For some reason Composer writes all output to `stderr`.

Here's the output of `./target/debug/topgrade --verbose --only composer`:
```
―― 09:28:32 - Composer ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-05-10T07:28:39.835Z TRACE topgrade::executor   > Output of "/usr/local/bin/composer" "global" "update": Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "Changed current directory to /Users/morten/.composer\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nPackage operations: 4 installs, 0 updates, 0 removals\n  - Installing alecrabbit/php-wcwidth (0.0.7): Loading from cache\n  - Installing alecrabbit/php-cli-tools (0.6.0): Loading from cache\n  - Installing alecrabbit/php-console-colour (0.10.0): Loading from cache\n  - Installing alecrabbit/php-console-spinner (0.53.0): Loading from cache\nWriting lock file\nGenerating optimized autoload files\n17 packages you are using are looking for funding.\nUse the `composer fund` command to find out more!\n" }

―― 09:28:39 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
composer: OK
```

**Comment by r-darwish** [comment]
Oh, the output is in stderr. I'll print that as well.

**Comment by r-darwish** [comment]
@mortenscheel can you check again?

**Comment by mortenscheel** [comment]
@r-darwish Yup. Now it works perfectly. Thanks!

**Comment by mortenscheel** [comment]
Yup, the output works now. Thanks!
Now we just need to also check if stderr contains "valet".

**Pull request merged**
