### PR TITLE
Remove trailing whitespace in emacs.el

### PR DESCRIPTION
**Pull request by HMPerson1**
Previously, the emacs step would fail with `Trailing garbage following expression:  `. This fixes that.

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles
- [x] The code passes rustfmt
- [x] The code passes clippy
- [x] The code passes tests
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
I have a vague memory that adding a final newline will break the Emacs step, but I don't use Emacs anymore to check. Are you sure that this is working?

**Comment by HMPerson1** [comment]
Yes, I tested this locally.

**Comment by r-darwish** [comment]
I see. Since it's not urgent in any means I will try to find my time to reinstall my Emacs configuration and figure out what was wrong with it.

**Comment by HMPerson1** [comment]
(In the meantime, could you [label this as `hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/details#rules)?)

**Comment by r-darwish** [comment]
> (In the meantime, could you [label this as `hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/details#rules)?)

No. Make a real contribution of you want to get a shirt

**Comment by r-darwish** [comment]
Since no other Emacs user complained about this bug I'm going to close this. If this is something that happens specifically in your system please provide some more information about which Emacs version are you running in which operating system.

**Comment by HMPerson1** [comment]
I was using Emacs 26.3 on Debian on WSL2, and I could reproduce the trailing whitespace error with just `emacs --batch --eval "(print 0) "`, though it seems that a few weeks ago, Debian unstable [updated to Emacs 27.1](https://tracker.debian.org/news/1186150/accepted-emacs-12711-2-source-into-unstable/), which now seems to be okay with trailing whitespace, so I guess this isn't needed anymore.

**Pull request closed without merging**
