### PR TITLE
Add Deno support (fix #526)

### LINKED ISSUE #526: Please add deno upgrade
**I want to suggest a new step**

Hi. Thanks for providing such a nice piece of software. I use it regularly! 

***Which tool is this about? Where is its repository?***

It would be great if topgrade could upgrade `deno`. 

https://deno.land

***Which operating systems are supported by this tool?***

Linux, Windows, Mac 

***What should Topgrade do to figure out if the tool needs to be invoked?***

`deno version` will show that deno is installed. 

***Which exact commands should Topgrade run?***

`deno upgrade`

**More information**
- Assuming that someone else implements the feature, please state if you know
  how to test it from a side branch of Topgrade

I am very much willing to test this myself if it's implemented! I have access to all three operating systems.

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@Terkwood can you please test this change?

**Comment by Terkwood** [comment]
Absolutely!! 🏁

**Comment by Terkwood** [comment]
Testing progress:

- [ ] works on linux (popOS/ubuntulike)
- [ ] works on mac
- [ ] works on windows

**Comment by Terkwood** [comment]
I opened a new PR in #530 which swaps `deno update` for `deno upgrade`.  Thanks very much for raising this so quickly, it was very easy to make the edit!

**Comment by r-darwish** [comment]
Superseded by #530

**Pull request closed without merging**
