### PR TITLE
"Ultimate vimrc" support

### LINKED ISSUE #856: "Ultimate vimrc" support
### Which tool is this about? Where is its repository?

This is about the "Ultimate vimrc": https://github.com/amix/vimrc

### Which operating systems are supported by this tool?

All

### What should Topgrade do to figure out if the tool needs to be invoked?

Check if ~/.vim_runtime exists `[[ -d ~/.vim_runtime ]]`. Technically it can be installed anywhere but this is the default one.

### Which exact commands should Topgrade run?

```bash
cd ~/.vim_runtime
git reset --hard
git clean -d --force
git pull --rebase
python update_plugins.py  # use python3 if python is unavailable
```

## More information

Instead of this, an alternative would be custom steps. I don't see docs on that though.

### PR DESCRIPTION
**Pull request by r-darwish**
Fixes #856

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles (`cargo build`)
- [ ] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [ ] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@Samisafool can you please test this branch?

**Comment by Samisafool** [comment]
It gets to:

```
HEAD is now at 5108ca4e fix: typo (#678)
Already up to date.
```

But then prompts me to retry (Like it failed somehow?).

**Comment by r-darwish** [comment]
Can you run Topgrade with `-v` and paste the output?

**Comment by Samisafool** [comment]
`     ctx.run_type().execute(python).current_dir(update_plugins).check_run()?;`

This should be:

```rust
     ctx.run_type()
    .execute(&python)
    .current_dir(&update_plugins)
    .check_run()?;
```

And for `-v`:

```
―― 16:36:00 - Vim ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-04-23T11:06:00.796Z DEBUG topgrade::steps::vim > Wrote vim script to "/tmp/.tmpstUOMm"
not found in 'runtimepath': "lang/menu_en.utf-8.vim"
line 11: could not source "/home/arch/.vim_runtime/my_configs.vim"
not found in 'packpath': "pack/*/start/*"
Error detected while processing /home/arch/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without allowing argumentsnot found in 'packpath': "pack/*/start/*"
Reading viminfo file "/home/arch/.viminfo" info oldfiles 
Writing viminfo file "/home/arch/.viminfo"Plugins upgraded
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "Neovim"
 2022-04-23T11:06:00.953Z DEBUG topgrade::utils      > Detected "/usr/bin/nvim" as "nvim"
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "voom"
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "Kakoune"
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "npm"
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "pnpm"
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "Containers"
 2022-04-23T11:06:00.953Z DEBUG topgrade::runner     > Step "deno"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "composer"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "krew"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "gem"
 2022-04-23T11:06:00.954Z DEBUG topgrade::utils      > Detected "/usr/bin/gem" as "gem"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "haxelib"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "sheldon"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "rtcl"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "bin"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "gcloud"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "micro"
 2022-04-23T11:06:00.954Z DEBUG topgrade::runner     > Step "raco"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "spicetify"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "GitHub CLI Extensions"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "toolbx"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "Flatpak"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "snap"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "pacstall"
 2022-04-23T11:06:00.955Z DEBUG topgrade::runner     > Step "Pacman files DB"

―― 16:36:00 - Pacman files DB ――――――――――――――――――――――――――――――――――――――――――――――――――

```

And now, somehow it says
```
―― 16:34:52 - Vim ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Plugins upgraded
```

Since I rebuilt topgrade? Weird.

**Comment by Samisafool** [comment]
```
―― 16:39:30 - Vim ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-04-23T11:09:30.452Z DEBUG topgrade::steps::vim > Wrote vim script to "/tmp/.tmpSoGiZY"
not found in 'runtimepath': "lang/menu_en.utf-8.vim"
line 11: could not source "/home/arch/.vim_runtime/my_configs.vim"
not found in 'packpath': "pack/*/start/*"
Error detected while processing /home/arch/.vim_runtime/sources_non_forked/tlib/plugin/02tlib.vim:
line   77: E1208: -complete used without allowing argumentsnot found in 'packpath': "pack/*/start/*"
Reading viminfo file "/home/arch/.viminfo" info oldfiles 
Writing viminfo file "/home/arch/.viminfo"Plugins upgraded
 2022-04-23T11:09:30.830Z DEBUG topgrade::runner     > Step "Neovim"
 2022-04-23T11:09:30.830Z DEBUG topgrade::utils      > Detected "/usr/bin/nvim" as "nvim"
 2022-04-23T11:09:30.830Z DEBUG topgrade::runner     > Step "vim"
 2022-04-23T11:09:30.830Z DEBUG topgrade::utils      > Path "/home/arch/.vim_runtime" exists
 2022-04-23T11:09:30.830Z DEBUG topgrade::utils      > Detected "/usr/bin/git" as "git"
 2022-04-23T11:09:30.830Z DEBUG topgrade::utils      > Detected "/usr/bin/python3" as "python3"
 2022-04-23T11:09:30.830Z DEBUG topgrade::utils      > Path "/home/arch/.vim_runtime/update_plugins.py" exists

―― 16:39:30 - The Ultimate vimrc ―――――――――――――――――――――――――――――――――――――――――――――――
 2022-04-23T11:09:30.830Z DEBUG topgrade::executor   > Running "/usr/bin/git" "reset" "--hard"
HEAD is now at ab92a1d4 Revert back to peaksea
 2022-04-23T11:09:30.854Z DEBUG topgrade::executor   > Running "/usr/bin/git" "clean" "-d" "--force"
 2022-04-23T11:09:30.859Z DEBUG topgrade::executor   > Running "/usr/bin/git" "pull" "--rebase"
Updating ab92a1d4..5108ca4e
Fast-forward
 README.md                                                             |   19 +-
 sources_non_forked/ale/ale_linters/ansible/ansible_lint.vim           |    3 +-
 sources_non_forked/ale/ale_linters/clojure/clj_kondo.vim              |    2 +-
 sources_non_forked/ale/ale_linters/dockerfile/hadolint.vim            |   10 +-
 sources_non_forked/ale/ale_linters/eruby/erblint.vim                  |   51 +
 sources_non_forked/ale/ale_linters/javascript/deno.vim                |   11 +
 sources_non_forked/ale/ale_linters/json/eslint.vim                    |   16 +
 sources_non_forked/ale/ale_linters/json5/eslint.vim                   |   16 +
 sources_non_forked/ale/ale_linters/jsonc/eslint.vim                   |   16 +
 sources_non_forked/ale/ale_linters/jsonnet/jsonnet_lint.vim           |   59 +
 sources_non_forked/ale/ale_linters/jsonnet/jsonnetfmt.vim             |   52 +
 sources_non_forked/ale/ale_linters/mail/languagetool.vim              |    2 +-
 sources_non_forked/ale/ale_linters/markdown/languagetool.vim          |    2 +-
 sources_non_forked/ale/ale_linters/python/flakehell.vim               |  175 ++
 sources_non_forked/ale/ale_linters/python/pyre.vim                    |   12 +-
 sources_non_forked/ale/ale_linters/robot/rflint.vim                   |   46 +
 sources_non_forked/ale/ale_linters/ruby/ruby.vim                      |    2 +-
 sources_non_forked/ale/ale_linters/thrift/thriftcheck.vim             |   46 +
 sources_non_forked/ale/ale_linters/yaml/circleci.vim                  |    2 +-
 sources_non_forked/ale/ale_linters/zeek/zeek.vim                      |   22 +
 sources_non_forked/ale/autoload/ale/codefix.vim                       |   18 +-
 sources_non_forked/ale/autoload/ale/completion.vim                    |    9 +-
 sources_non_forked/ale/autoload/ale/fix/registry.vim                  |   25 +
 sources_non_forked/ale/autoload/ale/fixers/dhall_format.vim           |    9 +-
 sources_non_forked/ale/autoload/ale/fixers/dhall_freeze.vim           |   12 +-
 sources_non_forked/ale/autoload/ale/fixers/dhall_lint.vim             |    9 +-
 sources_non_forked/ale/autoload/ale/fixers/dotnet_format.vim          |   18 +
 sources_non_forked/ale/autoload/ale/fixers/erblint.vim                |   40 +
 sources_non_forked/ale/autoload/ale/fixers/golines.vim                |   21 +
 sources_non_forked/ale/autoload/ale/fixers/isort.vim                  |   56 +-
 sources_non_forked/ale/autoload/ale/fixers/jsonnetfmt.vim             |   18 +
 sources_non_forked/ale/autoload/ale/fixers/purs_tidy.vim              |   24 +
 sources_non_forked/ale/autoload/ale/fixers/rubocop.vim                |    2 -
 sources_non_forked/ale/autoload/ale/handlers/cppcheck.vim             |   14 +-
 sources_non_forked/ale/autoload/ale/handlers/sml.vim                  |   22 +-
 sources_non_forked/ale/autoload/ale/hover.vim                         |    4 +-
 sources_non_forked/ale/autoload/ale/lsp.vim                           |   20 +
 sources_non_forked/ale/autoload/ale/lsp/message.vim                   |   11 +-
 sources_non_forked/ale/autoload/ale/lsp_linter.vim                    |   28 +-
 sources_non_forked/ale/autoload/ale/python.vim                        |    1 +
 sources_non_forked/ale/autoload/ale/util.vim                          |    4 +
 sources_non_forked/ale/autoload/ale/virtualtext.vim                   |   42 +-
 sources_non_forked/ale/doc/ale-cs.txt                                 |   33 +
 sources_non_forked/ale/doc/ale-development.txt                        |    3 +-
 sources_non_forked/ale/doc/ale-dhall.txt                              |   12 +-
 sources_non_forked/ale/doc/ale-eruby.txt                              |   21 +
 sources_non_forked/ale/doc/ale-go.txt                                 |   17 +
 sources_non_forked/ale/doc/ale-javascript.txt                         |    5 +
 sources_non_forked/ale/doc/ale-json.txt                               |    9 +
 sources_non_forked/ale/doc/ale-json5.txt                              |   15 +
 sources_non_forked/ale/doc/ale-jsonc.txt                              |   15 +
 sources_non_forked/ale/doc/ale-jsonnet.txt                            |   43 +
 sources_non_forked/ale/doc/ale-purescript.txt                         |   27 +
 sources_non_forked/ale/doc/ale-python.txt                             |   73 +
 sources_non_forked/ale/doc/ale-robot.txt                              |   16 +
 sources_non_forked/ale/doc/ale-supported-languages-and-tools.txt      |   43 +-
 sources_non_forked/ale/doc/ale-thrift.txt                             |   19 +
 sources_non_forked/ale/doc/ale-typescript.txt                         |    2 +-
 sources_non_forked/ale/doc/ale-zeek.txt                               |   23 +
 sources_non_forked/ale/doc/ale.txt                                    |   32 +-
 sources_non_forked/ale/supported-tools.md                             |   65 +-
 sources_non_forked/ctrlp.vim/autoload/ctrlp.vim                       |    1 +
 sources_non_forked/ctrlp.vim/readme.md                                |   18 +-
 sources_non_forked/dracula/INSTALL.md                                 |   12 +-
 sources_non_forked/dracula/after/plugin/dracula.vim                   |    8 +
 sources_non_forked/dracula/colors/dracula.vim                         |   17 +-
 sources_non_forked/dracula/doc/dracula.txt                            |    9 +-
 sources_non_forked/dracula/screenshot.png                             |  Bin 539018 -> 336007 bytes
 sources_non_forked/nerdtree/CHANGELOG.md                              |    6 +
 sources_non_forked/nerdtree/README.markdown                           |   32 +
 sources_non_forked/nerdtree/autoload/nerdtree.vim                     |    8 +-
 sources_non_forked/nerdtree/doc/NERDTree.txt                          |    8 +-
 sources_non_forked/nerdtree/nerdtree_plugin/fs_menu.vim               |    6 +-
 sources_non_forked/nerdtree/syntax/nerdtree.vim                       |   12 +-
 sources_non_forked/nginx.vim/README.md                                |    6 +
 sources_non_forked/nginx.vim/ftplugin/nginx.vim                       |    4 +
 sources_non_forked/nginx.vim/indent/nginx.vim                         |    2 +
 sources_non_forked/rust.vim/.github/workflows/ci.yml                  |    9 +
 sources_non_forked/rust.vim/.travis.yml                               |    7 -
 sources_non_forked/rust.vim/ISSUE_TEMPLATE.md                         |    1 +
 sources_non_forked/rust.vim/indent/rust.vim                           |    2 +
 sources_non_forked/rust.vim/test/run-tests                            |    6 +-
 sources_non_forked/tlib/.gitignore                                    |   13 +
 sources_non_forked/tlib/CHANGES.TXT                                   |  909 +++++++++
 sources_non_forked/{nginx.vim/LICENSE => tlib/LICENSE.TXT}            |    7 +-
 sources_non_forked/tlib/addon-info.json                               |    9 +
 sources_non_forked/tlib/autoload/tinykeymap/map/para_move.vim         |   12 +
 sources_non_forked/tlib/autoload/tlib/Filter_cnf.vim                  |    9 +-
 sources_non_forked/tlib/autoload/tlib/World.vim                       |  484 +++--
 sources_non_forked/tlib/autoload/tlib/agent.vim                       |  186 +-
 sources_non_forked/tlib/autoload/tlib/arg.vim                         |   74 +-
 sources_non_forked/tlib/autoload/tlib/assert.vim                      |    8 +-
 sources_non_forked/tlib/autoload/tlib/buffer.vim                      |   66 +-
 sources_non_forked/tlib/autoload/tlib/cache.vim                       |  250 ++-
 sources_non_forked/tlib/autoload/tlib/date.vim                        |   58 +-
 sources_non_forked/tlib/autoload/tlib/dictionary.vim                  |   38 +-
 sources_non_forked/tlib/autoload/tlib/dir.vim                         |    8 +-
 sources_non_forked/tlib/autoload/tlib/file.vim                        |  226 ++-
 sources_non_forked/tlib/autoload/tlib/input.vim                       |  306 ++-
 sources_non_forked/tlib/autoload/tlib/list.vim                        |   59 +-
 sources_non_forked/tlib/autoload/tlib/notify.vim                      |   18 +-
 sources_non_forked/tlib/autoload/tlib/number.vim                      |   13 +-
 sources_non_forked/tlib/autoload/tlib/persistent.vim                  |   15 +-
 sources_non_forked/tlib/autoload/tlib/progressbar.vim                 |   53 +-
 sources_non_forked/tlib/autoload/tlib/qfl.vim                         |   31 +-
 sources_non_forked/tlib/autoload/tlib/rx.vim                          |   10 +-
 sources_non_forked/tlib/autoload/tlib/selection.vim                   |   40 +
 sources_non_forked/tlib/autoload/tlib/string.vim                      |   62 +-
 sources_non_forked/tlib/autoload/tlib/sys.vim                         |   25 +-
 sources_non_forked/tlib/autoload/tlib/tag.vim                         |   15 +-
 sources_non_forked/tlib/autoload/tlib/time.vim                        |   19 +-
 sources_non_forked/tlib/autoload/tlib/trace.vim                       |  139 +-
 sources_non_forked/tlib/autoload/tlib/type.vim                        |  117 +-
 sources_non_forked/tlib/autoload/tlib/var.vim                         |   11 +-
 sources_non_forked/tlib/autoload/tlib/vcs.vim                         |  117 +-
 sources_non_forked/tlib/autoload/tlib/win.vim                         |   71 +-
 sources_non_forked/tlib/doc/tags                                      |  223 +++
 sources_non_forked/tlib/doc/tlib.txt                                  | 3307 +++++++++++--------------------
 sources_non_forked/tlib/etc/tpl_tlib.txt                              |   30 +
 sources_non_forked/tlib/macros/tlib.vim                               |   38 +
 sources_non_forked/tlib/plugin/02tlib.vim                             |   40 +-
 sources_non_forked/tlib/samples/tlib/input/tlib_input_list.vim        |   50 +
 sources_non_forked/tlib/scripts/create_crc_table.rb                   |   67 +
 sources_non_forked/tlib/spec/tlib/arg.vim                             |   66 +
 sources_non_forked/tlib/spec/tlib/date.vim                            |   61 +
 sources_non_forked/tlib/spec/tlib/dictionary.vim                      |   28 +
 sources_non_forked/tlib/spec/tlib/eval.vim                            |   27 +
 sources_non_forked/tlib/spec/tlib/file.vim                            |   59 +
 sources_non_forked/tlib/spec/tlib/hash.vim                            |   58 +
 sources_non_forked/tlib/spec/tlib/input.vim                           |  127 ++
 sources_non_forked/tlib/spec/tlib/list.vim                            |   67 +
 sources_non_forked/tlib/spec/tlib/rx.vim                              |   27 +
 sources_non_forked/tlib/spec/tlib/string.vim                          |   29 +
 sources_non_forked/tlib/spec/tlib/url.vim                             |   23 +
 sources_non_forked/tlib/spec/tlib/var.vim                             |   37 +
 sources_non_forked/vim-commentary/plugin/commentary.vim               |    9 +-
 sources_non_forked/vim-fugitive/autoload/fugitive.vim                 | 2264 ++++++++++++++-------
 sources_non_forked/vim-fugitive/doc/fugitive.txt                      |   88 +-
 sources_non_forked/vim-fugitive/plugin/fugitive.vim                   |  250 ++-
 sources_non_forked/vim-fugitive/syntax/fugitive.vim                   |   10 +-
 sources_non_forked/vim-gitgutter/README.mkd                           |   32 +
 sources_non_forked/vim-gitgutter/autoload/gitgutter.vim               |    4 +
 sources_non_forked/vim-gitgutter/autoload/gitgutter/highlight.vim     |    4 +-
 sources_non_forked/vim-gitgutter/doc/gitgutter.txt                    |   20 +
 sources_non_forked/vim-gitgutter/plugin/gitgutter.vim                 |    4 +-
 sources_non_forked/vim-indent-guides/LICENSE                          |   21 +
 sources_non_forked/vim-indent-guides/README.markdown                  |    2 +-
 sources_non_forked/vim-javascript/indent/javascript.vim               |    2 +-
 sources_non_forked/vim-multiple-cursors/Gemfile.lock                  |    2 +-
 sources_non_forked/vim-rhubarb/LICENSE                                |   20 +
 sources_non_forked/vim-rhubarb/autoload/rhubarb.vim                   |  330 +++
 sources_non_forked/vim-rhubarb/doc/rhubarb.txt                        |   17 +
 sources_non_forked/vim-rhubarb/plugin/rhubarb.vim                     |   53 +
 sources_non_forked/vim-ruby/ftdetect/ruby_extra.vim                   |    3 +
 sources_non_forked/vim-ruby/indent/ruby.vim                           |    2 +-
 sources_non_forked/vim-ruby/spec/syntax/comments_spec.rb              |    6 +
 sources_non_forked/vim-ruby/syntax/ruby.vim                           |    3 +-
 sources_non_forked/vim-snippets/UltiSnips/javascript.snippets         |   65 +
 sources_non_forked/vim-snippets/UltiSnips/markdown.snippets           |    6 +-
 sources_non_forked/vim-snippets/UltiSnips/python.snippets             |   29 +-
 sources_non_forked/vim-snippets/snippets/c.snippets                   |   27 +
 sources_non_forked/vim-snippets/snippets/cpp.snippets                 |    1 +
 sources_non_forked/vim-snippets/snippets/css.snippets                 |    1 +
 sources_non_forked/vim-snippets/snippets/go.snippets                  |    4 +-
 sources_non_forked/vim-snippets/snippets/html.snippets                |    6 +-
 .../vim-snippets/snippets/javascript/javascript.node.snippets         |    2 +-
 sources_non_forked/vim-snippets/snippets/python.snippets              |   19 +-
 sources_non_forked/vim-snippets/snippets/tex.snippets                 |    6 +-
 sources_non_forked/vim-surround/plugin/surround.vim                   |    2 +-
 update_plugins.py                                                     |    7 +-
 vimrcs/basic.vim                                                      |   28 +-
 vimrcs/plugins_config.vim                                             |   10 +-
 172 files changed, 8749 insertions(+), 4070 deletions(-)
 create mode 100644 sources_non_forked/ale/ale_linters/eruby/erblint.vim
 create mode 100644 sources_non_forked/ale/ale_linters/javascript/deno.vim
 create mode 100644 sources_non_forked/ale/ale_linters/json/eslint.vim
 create mode 100644 sources_non_forked/ale/ale_linters/json5/eslint.vim
 create mode 100644 sources_non_forked/ale/ale_linters/jsonc/eslint.vim
 create mode 100644 sources_non_forked/ale/ale_linters/jsonnet/jsonnet_lint.vim
 create mode 100644 sources_non_forked/ale/ale_linters/jsonnet/jsonnetfmt.vim
 create mode 100644 sources_non_forked/ale/ale_linters/python/flakehell.vim
 create mode 100644 sources_non_forked/ale/ale_linters/robot/rflint.vim
 create mode 100644 sources_non_forked/ale/ale_linters/thrift/thriftcheck.vim
 create mode 100644 sources_non_forked/ale/ale_linters/zeek/zeek.vim
 create mode 100644 sources_non_forked/ale/autoload/ale/fixers/dotnet_format.vim
 create mode 100644 sources_non_forked/ale/autoload/ale/fixers/erblint.vim
 create mode 100644 sources_non_forked/ale/autoload/ale/fixers/golines.vim
 create mode 100644 sources_non_forked/ale/autoload/ale/fixers/jsonnetfmt.vim
 create mode 100644 sources_non_forked/ale/autoload/ale/fixers/purs_tidy.vim
 create mode 100644 sources_non_forked/ale/doc/ale-json5.txt
 create mode 100644 sources_non_forked/ale/doc/ale-jsonc.txt
 create mode 100644 sources_non_forked/ale/doc/ale-jsonnet.txt
 create mode 100644 sources_non_forked/ale/doc/ale-robot.txt
 create mode 100644 sources_non_forked/ale/doc/ale-zeek.txt
 create mode 100644 sources_non_forked/rust.vim/.github/workflows/ci.yml
 delete mode 100644 sources_non_forked/rust.vim/.travis.yml
 create mode 100644 sources_non_forked/tlib/.gitignore
 create mode 100644 sources_non_forked/tlib/CHANGES.TXT
 rename sources_non_forked/{nginx.vim/LICENSE => tlib/LICENSE.TXT} (99%)
 create mode 100644 sources_non_forked/tlib/addon-info.json
 create mode 100644 sources_non_forked/tlib/autoload/tinykeymap/map/para_move.vim
 create mode 100644 sources_non_forked/tlib/autoload/tlib/selection.vim
 create mode 100644 sources_non_forked/tlib/doc/tags
 create mode 100644 sources_non_forked/tlib/etc/tpl_tlib.txt
 create mode 100644 sources_non_forked/tlib/macros/tlib.vim
 create mode 100644 sources_non_forked/tlib/samples/tlib/input/tlib_input_list.vim
 create mode 100644 sources_non_forked/tlib/scripts/create_crc_table.rb
 create mode 100644 sources_non_forked/tlib/spec/tlib/arg.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/date.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/dictionary.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/eval.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/file.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/hash.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/input.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/list.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/rx.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/string.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/url.vim
 create mode 100644 sources_non_forked/tlib/spec/tlib/var.vim
 create mode 100644 sources_non_forked/vim-indent-guides/LICENSE
 create mode 100644 sources_non_forked/vim-rhubarb/LICENSE
 create mode 100644 sources_non_forked/vim-rhubarb/autoload/rhubarb.vim
 create mode 100644 sources_non_forked/vim-rhubarb/doc/rhubarb.txt
 create mode 100644 sources_non_forked/vim-rhubarb/plugin/rhubarb.vim
 2022-04-23T11:09:31.536Z DEBUG topgrade::executor   > Running "/usr/bin/python3"
 2022-04-23T11:09:31.537Z DEBUG topgrade::runner     > Step "vim" failed: Not a directory (os error 20)
 2022-04-23T11:09:31.537Z DEBUG topgrade::terminal   > Desktop notification: vim failed

Retry? (y)es/(N)o/(s)hell/(q)uit
```

There.

`     ctx.run_type().execute(python).current_dir(update_plugins).check_run()?;`

This should probably be:

```rust
     ctx.run_type()
    .execute(&python)
    .current_dir(&update_plugins)
    .check_run()?;
```

**Comment by r-darwish** [comment]
I pushed a fix. Can you please try again?

**Comment by Samisafool** [comment]
```
thread 'main' panicked at 'vim already reported', src/report.rs:37:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With that env var:

```
thread 'main' panicked at 'vim already reported', src/report.rs:37:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.60.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1.60.0/library/core/src/panicking.rs:143:14
   2: topgrade::report::Report::push_result
             at ./topgrade/src/report.rs:37:13
   3: topgrade::runner::Runner::execute
             at ./topgrade/src/runner.rs:39:21
   4: topgrade::run
             at ./topgrade/src/main.rs:323:5
   5: topgrade::main
             at ./topgrade/src/main.rs:463:11
   6: core::ops::function::FnOnce::call_once
             at /rustc/1.60.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

With THAT one:

```
thread 'main' panicked at 'vim already reported', src/report.rs:37:13
stack backtrace:
   0:     0x55c2269b7b3c - std::backtrace_rs::backtrace::libunwind::trace::h4c82c30effa1ec8b
                               at /rustc/1.60.0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c2269b7b3c - std::backtrace_rs::backtrace::trace_unsynchronized::h04f51b94feda398c
                               at /rustc/1.60.0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c2269b7b3c - std::sys_common::backtrace::_print_fmt::h83c260b7e0b0e807
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55c2269b7b3c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4c69548d53cef23e
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55c2269e0f4c - core::fmt::write::he1f7c3e09b6d48b1
                               at /rustc/1.60.0/library/core/src/fmt/mod.rs:1190:17
   5:     0x55c2269b2601 - std::io::Write::write_fmt::h7f5865fb08a452b9
                               at /rustc/1.60.0/library/std/src/io/mod.rs:1657:15
   6:     0x55c2269ba635 - std::sys_common::backtrace::_print::hd7f28ad4b7c7f649
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55c2269ba635 - std::sys_common::backtrace::print::hda6514e610876808
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55c2269ba635 - std::panicking::default_hook::{{closure}}::hec9b2f020ff35128
                               at /rustc/1.60.0/library/std/src/panicking.rs:295:22
   9:     0x55c2269ba2f4 - std::panicking::default_hook::hd76a5748cebf86d7
                               at /rustc/1.60.0/library/std/src/panicking.rs:314:9
  10:     0x55c2269bad68 - std::panicking::rust_panic_with_hook::h372a0c94f5d85a2f
                               at /rustc/1.60.0/library/std/src/panicking.rs:698:17
  11:     0x55c2269baa77 - std::panicking::begin_panic_handler::{{closure}}::h6bef164c07c5cd1d
                               at /rustc/1.60.0/library/std/src/panicking.rs:588:13
  12:     0x55c2269b7fd4 - std::sys_common::backtrace::__rust_end_short_backtrace::ha06d828e2bf3aa2d
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55c2269ba799 - rust_begin_unwind
                               at /rustc/1.60.0/library/std/src/panicking.rs:584:5
  14:     0x55c22630cb63 - core::panicking::panic_fmt::h95a16302ac706f92
                               at /rustc/1.60.0/library/core/src/panicking.rs:143:14
  15:     0x55c226315d09 - topgrade::report::Report::push_result::hc982647ee22fdc01
                               at /home/arch/topgrade/src/report.rs:37:13
  16:     0x55c22649c62c - topgrade::runner::Runner::execute::h7630d2e23fc02d72
                               at /home/arch/topgrade/src/runner.rs:39:21
  17:     0x55c2263e4c1b - topgrade::run::h8713a18ca75a4737
                               at /home/arch/topgrade/src/main.rs:323:5
  18:     0x55c2263e719c - topgrade::main::hcc4c0fbcf0f453b8
                               at /home/arch/topgrade/src/main.rs:463:11
  19:     0x55c22646214b - core::ops::function::FnOnce::call_once::had724c603e120c0e
                               at /rustc/1.60.0/library/core/src/ops/function.rs:227:5
  20:     0x55c22645f7ae - std::sys_common::backtrace::__rust_begin_short_backtrace::h5aa33aafbe0f56eb
                               at /rustc/1.60.0/library/std/src/sys_common/backtrace.rs:122:18
  21:     0x55c22635e241 - std::rt::lang_start::{{closure}}::h254f4caca3049854
                               at /rustc/1.60.0/library/std/src/rt.rs:145:18
  22:     0x55c2269b72ee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he81739e93730d87f
                               at /rustc/1.60.0/library/core/src/ops/function.rs:259:13
  23:     0x55c2269b72ee - std::panicking::try::do_call::haab80c588b564f17
                               at /rustc/1.60.0/library/std/src/panicking.rs:492:40
  24:     0x55c2269b72ee - std::panicking::try::h44df61bdf16d5e2d
                               at /rustc/1.60.0/library/std/src/panicking.rs:456:19
  25:     0x55c2269b72ee - std::panic::catch_unwind::h5a4755568a112d4c
                               at /rustc/1.60.0/library/std/src/panic.rs:137:14
  26:     0x55c2269b72ee - std::rt::lang_start_internal::{{closure}}::hd1cd8cace1e688e2
                               at /rustc/1.60.0/library/std/src/rt.rs:128:48
  27:     0x55c2269b72ee - std::panicking::try::do_call::h2a95c2966749f5f5
                               at /rustc/1.60.0/library/std/src/panicking.rs:492:40
  28:     0x55c2269b72ee - std::panicking::try::hd43011e2f8131e56
                               at /rustc/1.60.0/library/std/src/panicking.rs:456:19
  29:     0x55c2269b72ee - std::panic::catch_unwind::hd291d3c47494d6cf
                               at /rustc/1.60.0/library/std/src/panic.rs:137:14
  30:     0x55c2269b72ee - std::rt::lang_start_internal::h97283ffe4f4e7a74
                               at /rustc/1.60.0/library/std/src/rt.rs:128:20
  31:     0x55c22635e210 - std::rt::lang_start::h71196d43fd3afe3f
                               at /rustc/1.60.0/library/std/src/rt.rs:144:17
  32:     0x55c2263e732c - main
  33:     0x7fc528a9b310 - __libc_start_call_main
  34:     0x7fc528a9b3c1 - __libc_start_main@GLIBC_2.2.5
  35:     0x55c22630d3e5 - _start
  36:                0x0 - <unknown>
```

**Comment by r-darwish** [comment]
Pushed another fix

**Comment by Samisafool** [comment]
Worked perfectly this time!

**Review by Samisafool — APPROVED** [review]

**Pull request merged**
