### PR TITLE
Add an option for self-updating composer (fix #318)

### LINKED ISSUE #318: Composer should uprade itself
I just noticed that my composer executable was outdated many months and I got an email about Github API deprecated use. That was fixed in the last composer release https://github.com/composer/composer/releases/tag/1.9.3 , but `topgrade` does not upgrade composer itself. I think it should?

A recommended global installation of composer is in /usr/local/bin on Linux/MacOs/Unix, see https://getcomposer.org/doc/00-intro.md#globally . Composer has a built in slef-update command, so it should be enough to run `sudo composer self-update`.

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
@klausi please test this change by putting the following snippet in your `topgrade.toml`:

```toml
[composer]
self_update = true
```

**Comment by klausi** [comment]
Thanks, it works with 2 minor problems:

1. It asks you for sudo again. I already typed in my sudo password at the System update (APT) part. Topgrade should remember the sudo password for 5 minutes and not ask for it twice in 1 command run. Maybe that is a separate issue?
2. There is no output:
```
―― 13:52:29 - Composer ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[sudo] password for klausi: 

―― 13:52:35 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
...
```
Did it upgrade Composer or not? Was it successful or not? Maybe that is also by design?

**Comment by r-darwish** [comment]
1. We're trying to think about a solution in #337. Sadly, Topgrade doesn't control the sudo timeout.
2. I pushed a fix for that. Can you please pull and check again?

**Comment by klausi** [comment]
Thank you, output looking good now!

I see, so the sudo thing is a bit annoying. Can you prevent asking for sudo if there is no global composer update anyway? If current composer version is latest version do not ask for sudo.

**Comment by r-darwish** [comment]
@klausi is there any way to check it by running composer?

**Comment by klausi** [comment]
You could run `composer self-update` without sudo. If exit status is 0 then it means there is no update. Otherwise there is an error, probably `rename(/usr/local/bin/composer): failed to open stream: Permission denied` and the exit status is 1. Then you could re-run `self-update` with sudo.

**Comment by r-darwish** [comment]
I implemented your suggestion. Please check.

**Comment by klausi** [comment]
Works for me, thanks!

The git commits are a bit confusing to review here, looks like you mixed in some unrelated changes?

**Comment by r-darwish** [comment]
I merged it with the master branch. I perform squash merges so it will be a single commit when merged. I suggest that you look at the changes tab instead of the commit tab

**Comment by klausi** [comment]
cool, I like squash merges :-)

You probably did not merge in the recent master branch changes into this branch, that's why I see lots of unrelated changes at the changes tab.

**Pull request merged**
