### PR TITLE
Replace the apt step with nala if installed.

### LINKED ISSUE #897: Replace the apt step with nala if installed.
### Which tool is this about? Where is its repository?
It's about "[nala](https://salsa.debian.org/volian-team/nala)" an `apt` frontend replacement with optimized terminal output and added features like automatically choosing the best mirror or parallelized downloads for faster updates.
### Which operating systems are supported by this tool?
Any Linux distro that uses apt.  
### What should Topgrade do to figure out if the tool needs to be invoked?
I think checking for the `nala` command in the PATH should be sufficient. 
### Which exact commands should Topgrade run?
Running `sudo nala upgrade` does the job.

### PR DESCRIPTION
**Pull request by r-darwish**
Fixes #897

## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles (`cargo build`)
- [ ] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [ ] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@RayJW can you please test this branch?

**Comment by RayJW** [comment]
At the moment, it updates the sources with `nala update` however it fails at: 

`Usage: nala [OPTIONS] COMMAND [ARGS]...
Try 'nala -h' for help.

Error: No such command 'dist-upgrade'.
`

This is because the commands don't map 1 to 1 with apt. It would be sufficient to just run `nala upgrade` as this updates the sources before running a system upgrade.

**Comment by r-darwish** [comment]
@RayJW I pushed a fix. Can you please try again?

**Comment by RayJW** [comment]
@r-darwish The upgrade process now works, however since upgrade also involves an update, the sources now get updated twice which is a waste of time. The easiest solution would be to run `sudo nala upgrade --no-update` so there don't have to be more checks to decide if running an update is necessary. Alternatively, `sudo nala update` can be skipped and only upgrade without any flags should be run. 
Either solution would work.

**Comment by r-darwish** [comment]
> @r-darwish The upgrade process now works, however since upgrade also involves an update, the sources now get updated twice which is a waste of time. The easiest solution would be to run `sudo nala upgrade --no-update` so there don't have to be more checks to decide if running an update is necessary. Alternatively, `sudo nala update` can be skipped and only upgrade without any flags should be run. Either solution would work.

I pushed a fix to that as well

**Comment by RayJW** [comment]
@r-darwish Everything works as expected now. 
Maybe it would actually make sense to use the second solution of skipping `sudo nala update` and then run `sudo nala upgrade` because now the message reporting how many updates are available is duplicated. However, this is more of an improvement and not critical. Thanks for your work either way!

**Comment by RayJW** [comment]
@r-darwish Now everything works like a charm. Thank you for your work!

**Pull request merged**
