### PR TITLE
Run fwupdmgr update (fix #668)

### LINKED ISSUE #668: Why is "fwupdmgr update" not run?
Quick question. I see on the Wiki that `fwupdmgr` is run, but `fwupdmgr update` is not. I was wondering if you could explain why. I was thinking I'd add it as a custom step, but not if it's problematic in some way.

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@openjck can you please test this change?

**Comment by openjck** [comment]
Looks good to me. The only small issue is that it looks like it doesn't support `assume_yes` yet.

**Comment by r-darwish** [comment]
Should we pass `-y` to `fwupdmgr`?

**Comment by openjck** [comment]
It looks like `-y` or `--assume-yes` is the option, yeah

**Comment by r-darwish** [comment]
I pushed an update that passes `-y`. Can you please check?

**Comment by openjck** [comment]
LGTM :+1:

**Pull request merged**
