### PR TITLE
Add support to Zim

### PR DESCRIPTION
**Pull request by ericbn**
Zim is a Zsh configuration framework. See https://github.com/zimfw/zimfw

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles
- [x] The code passes rustfmt
- [x] The code passes clippy
- [ ] The code passes tests
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Review by r-darwish — APPROVED** [review]
Thanks

**Review by r-darwish — CHANGES_REQUESTED** [review]
Please fix the clippy suggestion

**Comment by ericbn** [comment]
Hi @r-darwish. Done!

**Comment by ericbn** [comment]
Thanks for merging this, @r-darwish! You have a very cool project! I wonder why did you implement it in Rust. I feel it would be simpler and easier to customize if it was implemented in shell script. Any particular feature of Rust you're taking advantage of, if you don't mind me asking?

**Comment by r-darwish** [comment]
I really dislike shell scripting as a language, and some Topgrade features were hard to implement in shell. In addition, Topgrade has Windows as tier 1 support and that would be hard to achieve if it was written in bash.

**Comment by ericbn** [comment]
Got it, makes perfect sense. Thanks for the quick response!

**Pull request merged**
