### PR TITLE
Pacdiff doesn't need vim if $DIFFPROG is set

### LINKED ISSUE #811: Topgrade should consider other diff progs
Hi, just noticed you released v8.1.2 and the changelog says `Don't run pacdiff if vim isn't installed` and that's right because pacdiff works by default with `vimdiff`.
However, [pacdiff can also use other programs to show the differences](https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave#pacdiff) by setting the `$DIFFPROG` enviromment variable (I personally set my diffprog variable in `~/.profile` and then passed the variable through `sudo` by modifying `/etc/sudo.conf`).

### PR DESCRIPTION
**Pull request by MCOfficer**
## Standards checklist:

closes #811

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

@PolpOnline

### CODE REVIEW

**Review by r-darwish — CHANGES_REQUESTED** [review]
Please fix the clippy errors

**Comment by PolpOnline** [comment]
Can't build in Arch, the errors are the same from clippy

**Review by PolpOnline — APPROVED** [review]
From a functionality perspective (I'm not a rust dev) it works now.

**Comment by MCOfficer** [comment]
Seems like this was done in 3f12cf11f6ebec7117c9cc6f9d8ca819cf7c40fa

**Pull request closed without merging**
