### PR TITLE
zplugin was renamed to zinit

### PR DESCRIPTION
**Pull request by hugoh**
zplugin was renamed to zinit: https://github.com/zdharma/zinit/commit/1ca8f6856cfe5e56abc969eae8e2a5489feb3a65

* s/zplugin/zinit/
* Testing for $ZPFX instead of ZPLGM which is exported

### CODE REVIEW

**Comment by hugoh** [comment]
Tests are failing in files I did not touch, so I'll leave it there for now.

**Comment by r-darwish** [comment]
Thanks

**Comment by strangelittlemonkey** [comment]
I know this has already been merged but I’m not sure this is the best way to handle it. Checking their page it looks like the rename happened less than a month ago. What happens for the people that have it and it’s called zplugin and isn’t the new project name yet. It might be better to check for either and give one precedence over the other rather than to totally exclude the name, at least this early in a project renaming.

**Comment by hugoh** [comment]
That's a good point that both should really be checked.

**Comment by hugoh** [comment]
@strangelittlemonkey - I attempted to address this in #321

**Pull request merged**
