### PR TITLE
Support VSCodium (Fix #637)

### LINKED ISSUE #637: [Feature Request] Incorporate VS Codium client and extension updates
**I want to suggest a new step**
This may be, in actuality, two separate requests, however now that Topgrade can update VS Code, it likely can also update [VS Codium](https://vscodium.com) and it's extensions (via the [Open VSX Registry](https://open-vsx.org/)).

***Which tool is this about? Where is its repository?***
VS Codium is an OSS reimplimentation of VS Code, removing the non-OSS metrics and backend connections. It uses the following repository: [GitHub](https://github.com/VSCodium/vscodium)

***Which operating systems are supported by this tool?***
VS Codium can be installed on Windows 10, MacOS, and various Linux flavors: [Install Instructions](https://github.com/VSCodium/vscodium#download-install)

***What should Topgrade do to figure out if the tool needs to be invoked?***
Potentially can utilize existing VS Code upgrade commands and procedures, but pointing to a VS Codium installation.

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@AyoungDukie can you please test this change?

**Comment by AyoungDukie** [comment]
I would be happy to help, I'll give it a go later this evening after I get off my shift at work!

**Comment by SanchithHegde** [comment]
@r-darwish I just tested this change, VSCodium is detected as expected. Thank you!

**Comment by AyoungDukie** [comment]
Apologies for the slowness, was a little out of practice getting set up to test. The upgrade process seems to work! Two points (potentially for followup in a different bug/feature-request/pr:

1. When I tested on a machine that still had VS Code installed, it seems to identify VS Code and update that installation only (Easy workaround is to finish uninstalling VS Code first.
2. Just as an FYI, for me it will show the update step as "Visual Studio Code"
image
It does seem to be working through the updates nonetheless. 

Thanks for your work on this!

**Comment by r-darwish** [comment]
Yeah. I went for the most easy fix because I assumed people won't have have both, but I can make a better fix

**Comment by r-darwish** [comment]
@AyoungDukie I pushed a better fix which addresses these issues. Can you please check?

**Comment by AyoungDukie** [comment]
Can confirm with release 6.60 that, after re-installing code so that both are present, both Code and Codium are updated:
image

**Pull request merged**
