### PR TITLE
Use a vim script to upgrade vim

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
@openjck @cujomalainey @KokaKiwi - I tried creating a vim script that detects which plugin system you're using and use the appropriate one. However, this doesn't seem to work as expected. I see the `echo "one"` printing despite the fact that there's no such command as `PlugUpgrade1`, and the other echos do not appear. Does anyone knows enough vimscript to help with this PR?

**Comment by openjck** [comment]
I believe vimscript is like Bash in that execution continues even after an error is encountered. In this case, I believe line 1 raises an error but line 2 echoes "one" regardless.

**Comment by openjck** [comment]
I wonder if the `exists` calls are failing due to [this caveat](https://stackoverflow.com/a/5010399/4297741).

**Comment by cujomalainey** [comment]
Sorry I'm not a vim script expert.

**Comment by r-darwish** [comment]
I think I got it working. Can any of you please test this branch?

**Comment by openjck** [comment]
I'll take a look today or tomorrow. Thank you!

**Comment by openjck** [comment]
I'm sorry, I'm not very familiar with Rust. If you get a chance, can you please share instructions for testing this locally?

**Comment by openjck** [comment]
I ended up doing a `cargo install --path .`, it works well for me! :smiley:

**Pull request merged**
