### PR TITLE
Execute the user default shell when using remotes (fix #670)

### LINKED ISSUE #670: Remote option does not perform a full run
**What did you expect to happen?**
When using the remote option (remote_topgrades) and have no limitations (disable, only) set the remote topgrade should perform a full topgrade run.

**What actually happened?**
On my Raspberry Pi 4 only the system update runs when started remotely by my local PCs topgrade. However, when I use an SSH shell with the exact same command (`.cargo/bin/topgrade`) that is set for "remote_topgrade_path" in my TOML config file a full run is performed.

**Additional details:**
- On the local PC I use Windows 10.
- On the remote Raspberry Pi 4 Raspberry Pi OS 10 (buster) is running.
- On the PC topgrade has been installed by just unzipping the ZIP file to a local directory.
- On the Raspberry Pi 4 topgrade has been installed via "cargo install".

`.\topgrade.exe --dry-run` produces the following output for the remote section:
<details><pre>
―― 08:24:55 - Remote (raspi) ―――――――――――――――――――――――――――――――――――――――――――――――――――
Connecting to raspi...
Dry running: C:\Program Files\OpenSSH-Win64\ssh.EXE -t raspi -o ConnectTimeout=2 env TOPGRADE_PREFIX=raspi .cargo/bin/topgrade
</pre></details>

`topgrade -v` produces the following output (selection):
<details><pre>
 2021-03-16T07:29:35.584Z DEBUG topgrade::config > Configuration at C:\Users\username\AppData\Roaming\topgrade.toml
 2021-03-16T07:29:35.585Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: Some(["raspi"]), remote_topgrade_path: Some(".cargo/bin/topgrade"), ssh_arguments: Some("-o ConnectTimeout=2"), git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: Some(true), notify_each_step: None, accept_all_windows_updates: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None }), linux: Some(Linux { yay_arguments: None, trizen_arguments: None, dnf_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: Some(true) }), vagrant: None }
 2021-03-16T07:29:35.587Z DEBUG topgrade         > Version: 6.7.0
 2021-03-16T07:29:35.587Z DEBUG topgrade         > OS: x86_64-pc-windows-msvc
 2021-03-16T07:29:35.588Z DEBUG topgrade         > Args { inner: ["C:\\opt\\topgrade\\topgrade.exe", "-v"] }
 2021-03-16T07:29:35.588Z DEBUG topgrade         > Binary path: Ok("C:\\opt\\topgrade\\topgrade.exe")
 2021-03-16T07:29:35.589Z DEBUG topgrade         > Self Update: true
 2021-03-16T07:29:35.603Z DEBUG topgrade::utils  > Detected "C:\\Program Files\\Git\\cmd\\git.EXE" as "git"
 2021-03-16T07:29:35.621Z DEBUG topgrade::utils  > Cannot find "doas"
 2021-03-16T07:29:35.639Z DEBUG topgrade::utils  > Cannot find "sudo"
 2021-03-16T07:29:35.657Z DEBUG topgrade::utils  > Cannot find "gsudo"
 2021-03-16T07:29:35.675Z DEBUG topgrade::utils  > Cannot find "pkexec"

―― 08:29:35 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Topgrade is up-to-date
 2021-03-16T07:29:35.863Z DEBUG topgrade::utils  > Detected "C:\\Program Files\\PowerShell\\7\\pwsh.EXE" as "pwsh"
 2021-03-16T07:29:36.504Z TRACE topgrade::executor > Output of "C:\\Program Files\\PowerShell\\7\\pwsh.EXE" "-NoProfile" "-Command" "Split-Path $profile": Output { status: ExitStatus(ExitStatus(0)), stdout: "D:\\UserData\\username\\OneDrive\\Dokumente\\PowerShell\r\n", stderr: "" }
...
 2021-03-16T07:29:36.506Z DEBUG topgrade::runner   > Step "WSL"
 2021-03-16T07:29:36.509Z DEBUG topgrade::utils    > Detected "C:\\Windows\\System32\\wsl.EXE" as "wsl"
 2021-03-16T07:29:40.452Z TRACE topgrade::executor > Output of "C:\\Windows\\System32\\wsl.EXE" "bash" "-lc" "which topgrade": Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "" }
 2021-03-16T07:29:40.452Z DEBUG topgrade::runner   > Step "Remote (raspi)"
 2021-03-16T07:29:40.454Z DEBUG topgrade::utils    > Detected "C:\\Program Files\\OpenSSH-Win64\\ssh.EXE" as "ssh"
 2021-03-16T07:29:40.456Z DEBUG topgrade::executor > Running "wt" "ssh" "-t" "raspi" "-o" "ConnectTimeout=2" "env" "TOPGRADE_PREFIX=raspi" ".cargo/bin/topgrade" "--keep"
 2021-03-16T07:29:40.499Z DEBUG topgrade::runner   > Step "Windows App Store"
 2021-03-16T07:29:40.504Z DEBUG topgrade::utils    > Detected "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" as "powershell"
 2021-03-16T07:29:40.504Z DEBUG topgrade::runner   > Step "Chocolatey"
 2021-03-16T07:29:40.510Z DEBUG topgrade::utils    > Detected "C:\\ProgramData\\chocolatey\\bin\\choco.EXE" as "choco"
...
―― 08:31:30 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
WSL: SKIPPED: Could not find Topgrade installed in WSL
Remote (raspi): SKIPPED: Remote Topgrade launched in an external terminal
Windows App Store: SKIPPED: Sudo is required
Chocolatey: OK
Scoop: SKIPPED: Cannot find "scoop" in PATH
Git repositories: SKIPPED: No repositories to pull
Powershell Modules Update: OK
apm: SKIPPED: Cannot find "apm" in PATH
vscode: OK
vscodium: SKIPPED: Cannot find "codium" in PATH
fossil: SKIPPED: Cannot find "fossil" in PATH
rustup: SKIPPED: Cannot find "rustup" in PATH
.NET: SKIPPED: dotnet did not output packages
choosenim: SKIPPED: Cannot find "choosenim" in PATH
cargo: SKIPPED: Cannot find "cargo" in PATH
Flutter: SKIPPED: Cannot find "flutter" in PATH
Emacs: SKIPPED: Cannot find "emacs" in PATH
opam: SKIPPED: Cannot find "opam" in PATH
vcpkg: SKIPPED: Cannot find "vcpkg" in PATH
pipx: SKIPPED: Cannot find "pipx" in PATH
stack: SKIPPED: Cannot find "stack" in PATH
tlmgr: OK
myrepos: SKIPPED: Cannot find "mr" in PATH
jetpack: SKIPPED: Cannot find "jetpack" in PATH
vim: SKIPPED: Cannot find "vim" in PATH
Neovim: SKIPPED: Cannot find "nvim" in PATH
voom: SKIPPED: Cannot find "voom" in PATH
npm: OK
yarn: SKIPPED: Cannot find "yarn" in PATH
deno: SKIPPED: Cannot find "deno" in PATH
composer: SKIPPED: Cannot find "composer" in PATH
krew: SKIPPED: Cannot find "kubectl-krew" in PATH
gem: SKIPPED: Cannot find "gem" in PATH
sheldon: SKIPPED: Cannot find "sheldon" in PATH
rtcl: SKIPPED: Cannot find "rupdate" in PATH
gcloud: SKIPPED: Cannot find "gcloud" in PATH
micro: SKIPPED: Cannot find "micro" in PATH
Windows update: OK
 2021-03-16T07:31:30.575Z DEBUG topgrade::terminal           > Desktop notification: Topgrade finished sucessfully
</pre></details>

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@loehden can you please test if this change fixes your issue?

**Comment by loehden** [comment]
Hi @r-darwish, thanks for your timely response. I am using the provided EXE file on my PC. May you provide a pre-build EXE or tell me how to build one from the `remote-shell` tree?

**Comment by r-darwish** [comment]
https://github.com/r-darwish/topgrade/wiki/Running-Topgrade-from-source

**Comment by loehden** [comment]
Thanks for the the hint. Remote topgrade works like a charm now.

**Comment by r-darwish** [comment]
Seems like another bug. Does this not happen as well when you use the regular version of Topgrade?

**Comment by loehden** [comment]
It's the same when I am using `cargo run` on the `master` tree. So I guess it has to do with my build toolchain, since the provided EXE file does not show any error messages.

**Comment by r-darwish** [comment]
Weird. This should only happen if `powershell` is not in your PATH, which doesn't make much sense. Anyway, I'll merge this as the Windows panic seems unrelated.

**Comment by loehden** [comment]
Maybe it's because I used the git bash, even though I can run the powershell directly from it from any directory. However, thanks for the fix!

**Pull request merged**
