### PR TITLE
Skip git repos without remotes

### PR DESCRIPTION
**Pull request by dignati**
I have selected many git repos for automatic update by using a wide glob. Some of these repos don't have a remote yet so I always have to tell topgrade to ignore the failed pulls on these repos. I could probably just tell topgrade to always ignore errors in the git step but I think it would still show up as failed. 

This PR simply skips git repos without remotes but still logs a warning that this is happening. I would really like to see this merged, so let me know if I can improve anything!

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles
- [x] The code passes rustfmt
- [x] The code passes clippy
- [x] The code passes tests
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by dignati** [comment]
The clippy failures seem unrelated to my changes, not sure why they are showing up now.

**Comment by idanski** [comment]
Hey @dignati I believe these are new clippy (1.43) errors.
I opened a PR to fix them, you can rebase with my branch if you'd like. or just rebase with master after it is merged (which I believe will happen tomorrow).

**Comment by dignati** [comment]
@idanski Thanks for letting me know and fixing this so fast. I'll rebase from master tomorrow then.

**Comment by dignati** [comment]
The new failure in Azure Pipelines seems unrelated to this PR as well.

**Comment by r-darwish** [comment]
Thanks!

**Pull request merged**
