### PR TITLE
Split brew cask into a seperate step (fix #588)

### LINKED ISSUE #588: Please make brew casks updates as a separate step
**I want to suggest some general feature**
Topgrade should upgrade brew formulae and brew casks separately, not as a single step.
**Operating system**
MacOs Big Sur 11.1

**More information**
- Maybe it's just my case but I hope it's not. Mostly brew formulae has much more problems because of linkage, xcode dependency etc. and usually fails the step. But unlike formulae, casks are way more stable (mostly because they're monoliths with no dependencies) So the problem is obvious, If I have problem with brew formulae, I won't be able to upgrade brew casks via topgrade until I'll solve the formulae's problem, what is inconvenient sometimes. May I ask you to separate them from each other to avoid such a problem? Much appreciate it.

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@xxfatumxx please test this change

**Comment by xxfatumxx** [comment]
Hey @r-darwish, so now `topgrade` with no options looks like it operates with formulas and casks [separately](https://imgur.com/a/VZzDCiv), BUT I still cannot operate with them via `--only` and `--disable` key:
```
./target/debug/topgrade --only brew_formula
error: 'brew_formula' isn't a valid value for '--only <only>...'
	[possible values: asdf, atom, brew, cargo, chocolatey, choosenim, composer, custom_commands, deno, dotnet, emacs, firmware, flatpak, flutter, gcloud, gem, git_repos, go, home_manager, jetpack, krew, mac_ports, microsoft_auto_update, myrepos, nix, node, opam, pearl, pipx, pkg, powershell, remotes, restarts, rtcl, rustup, scoop, sdkman, sheldon, shell, snap, stack, system, tldr, tlmgr, tmux, vagrant, vcpkg, vim, wsl, yadm]

	Did you mean 'brew'?

USAGE:
    topgrade --only <only>...

For more information try --help
```

```
./target/debug/topgrade --only brew_cask
error: 'brew_cask' isn't a valid value for '--only <only>...'
	[possible values: asdf, atom, brew, cargo, chocolatey, choosenim, composer, custom_commands, deno, dotnet, emacs, firmware, flatpak, flutter, gcloud, gem, git_repos, go, home_manager, jetpack, krew, mac_ports, microsoft_auto_update, myrepos, nix, node, opam, pearl, pipx, pkg, powershell, remotes, restarts, rtcl, rustup, scoop, sdkman, sheldon, shell, snap, stack, system, tldr, tlmgr, tmux, vagrant, vcpkg, vim, wsl, yadm]

	Did you mean 'brew'?

USAGE:
    topgrade --only <only>...

For more information try --help
```
I hope this is temporarily and you're just checking if it works overall.
Also It would be nice if you'll add new steps to [help message](https://imgur.com/a/kSLFHtb) as well. Thank you so much.

**Comment by r-darwish** [comment]
@xxfatumxx I pushed new flags for controlling the individual steps

**Comment by xxfatumxx** [comment]
@r-darwish Thank you so much. Tested all scenarios and everything worked smoothly. Looking forward for release. Much appreciate it.

**Pull request merged**
