### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by jimman2003**
## Standards checklist:

- [X] The PR title is descriptive.
- [X] The code compiles (`cargo build`)
- [X] The code passes rustfmt (`cargo fmt`)
- [X] The code passes clippy (`cargo clippy`)
- [X] The code passes tests (`cargo test`)
- [X] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
Shouldn't `cargo.lock` be updated as well?

**Comment by jimman2003** [comment]
Yeah..forgot to commit Cargo.lock...

**Comment by MCOfficer** [comment]
Just wanted to say [Dependabot](https://dependabot.com/) is an option going forward.

**Comment by jimman2003** [comment]
Yeah! My prev experience is pretty good!

**Comment by jimman2003** [comment]
Can you merge for the time being?

**Pull request merged**
