### PR TITLE
Support Vim's package (fix #498)

### LINKED ISSUE #498: Support packer.nvim
**I want to suggest a new step**
***Which tool is this about? Where is its repository?***
packer.nvim: https://github.com/wbthomason/packer.nvim
***Which operating systems are supported by this tool?***
This is a neovim plugin manager
***What should Topgrade do to figure out if the tool needs to be invoked?***
see answer to next question
***Which exact commands should Topgrade run?***
Add this to `upgrade.vim`
```vim
if exists(":PackerUpdate")
    echo Packer
    PackerUpdate
endif
```

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@p00f can you please test this branch?

**Comment by p00f** [comment]
> @p00f can you please test this branch?

will do

**Comment by p00f** [comment]
It updates - proof https://gfycat.com/misguidedrelievedbluetonguelizard

but it doesn't echo Packer

**Comment by p00f** [comment]
Also I unnecesarily ran `cargo build`, how do I completely clean it up and switch to the AUR version again?

**Comment by r-darwish** [comment]
Please run it with `cargo run -- -v` so we can see the echo lines in the vim script

**Comment by p00f** [comment]
Yes it works, please merge this

**Pull request merged**
