### PR TITLE
asdf (fix #334)

### LINKED ISSUE #334: ASDF support
**Describe the feature**
***Are you suggesting a new step?***
- Which tool is this about? Where is its repository?

ASDF is similar to SDKMAN, but more extendable, and more pwowerful as it allows to define a sdk / language version in the shell, directory, by default, and automatically switches the version as defined when traversing the filesystem.

Site: https://asdf-vm.com/#/
GH: https://github.com/asdf-vm/asdf
Doc: https://asdf-vm.com/#/core-manage-asdf-vm

- Which operating systems are supported by this tool?

Linux and MacOs, not sure about windows

- What should Topgrade do to figure out if the tool needs to be invoked?
- Which exact commands should Topgrade run?

1. [Update ASDF](https://asdf-vm.com/#/core-manage-asdf-vm?id=update)
2. [Update ASDF plugins](https://asdf-vm.com/#/core-manage-plugins?id=update)

I'm not sure but maybe ask about lastest stable of the installed version. I believe _latest_ subcommand has been made available in v0.7.6, but may not be supported by all plugins.

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
@bric3 please test

**Comment by bric3** [comment]
@r-darwish nice !
I'm not enough familiar with rust to build from sources. How should I proceed ?

**Comment by r-darwish** [comment]
@bric3 
https://github.com/r-darwish/topgrade/wiki/Running-Topgrade-from-source

**Comment by bric3** [comment]
OK I didn't thought about the wiki.

So yes I confirm it works as expected.

**Pull request merged**
