### PR TITLE
On my laptop, the terminal separator line has been off by one every time.

### PR DESCRIPTION
**Pull request by jasikpark**
Changing `.checked_sub(3)` to `.checked_sub(4)` prevents the line separator from overflowing on my screen.

### Original
Screenshot 2019-03-15 19 24 55

### New
Screenshot 2019-03-15 19 24 58

### CODE REVIEW

**Comment by jasikpark** [comment]
bors r+ 

??

**Comment by jasikpark** [comment]
ah

**Comment by r-darwish** [comment]
thanks

**Pull request merged**
