### PR TITLE
Skip dotnet when no SDK is installed (fix #592)

### LINKED ISSUE #592: Dotnet tools upgrade fails if there are none installed.
**What did you expect to happen?**
Nothing

**What actually happened?**
It tried to upgrade .net tool ' ---------------------' which doesnt exist.

**Additional details:**
Installed topgrade on a fairly clean vm supplied by ms: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/
There are no global dotnet tools installed, thats probably causing parsing of the output to go haywire.

<details><pre>
error NU1101: Unable to find package ---------------------. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Tool '---------------------' failed to update due to the following:
The tool package could not be restored.
Tool '---------------------' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
</pre></details>

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@moritzrupp can you please check if this fixes your issue?

**Comment by moritzrupp** [comment]
I have cloned the repo and checkout out the `dotnet-fix` branch and ran topgrade with `cargo run -- -v`. It doesn't seem to fix the issue. Below is the output.

```powershell
PS > cargo run -- -v
...
2021-01-10T16:47:54.117Z DEBUG topgrade::runner     > Step ".NET"
2021-01-10T16:47:54.136Z DEBUG topgrade::utils      > Detected "C:\\Program Files\\dotnet\\dotnet.EXE" as "dotnet"
2021-01-10T16:47:54.149Z TRACE topgrade::executor   > Output of "C:\\Program Files\\dotnet\\dotnet.EXE" "tool" "list" "--global": Output { status: ExitStatus(ExitStatus(2147516561)), stdout: "", stderr: "  It was not possible to find any installed .NET Core SDKs\r\n  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:\r\n      https://aka.ms/dotnet-download\r\n" }
2021-01-10T16:47:54.151Z DEBUG topgrade::terminal   > Desktop notification: .NET failed

Retry? (y)es/(N)o/(s)hell
2021-01-10T16:49:57.678Z DEBUG topgrade::runner     > Step "choosenim"
...
```

**Comment by r-darwish** [comment]
@moritzrupp thanks for testing out. I pushed another change. I hope I got it right this time. Can you please check?

**Comment by moritzrupp** [comment]
I think this change did it. 👍 
This is the output:

```powershell
 MSYS ~/Development/topgrade (dotnet-fix)
$ cargo run -- -v --only dotnet
   Compiling topgrade v6.2.2 
    Finished dev [unoptimized + debuginfo] target(s) in 8.81s
     Running `target\debug\topgrade.exe -v --only dotnet`
 2021-01-11T10:25:54.870Z DEBUG topgrade::config > Configuration at \AppData\Roaming\topgrade.toml
 2021-01-11T10:25:54.878Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, post_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: Some([Wsl]), ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None, brew: None, linux: None, git: None, windows: None, vagrant: None }
 2021-01-11T10:25:54.880Z DEBUG topgrade         > Version: 6.2.2
 2021-01-11T10:25:54.880Z DEBUG topgrade         > OS: x86_64-pc-windows-msvc
 2021-01-11T10:25:54.880Z DEBUG topgrade         > Args { inner: ["target\\debug\\topgrade.exe", "-v", "--only", "dotnet"] }
 2021-01-11T10:25:54.881Z DEBUG topgrade         > Binary path: Ok("\\Development\\topgrade\\target\\debug\\topgrade.exe")
 2021-01-11T10:25:54.881Z DEBUG topgrade         > Self Update: false
 2021-01-11T10:25:54.897Z DEBUG topgrade::utils  > Detected "C:\\Program Files\\Git\\cmd\\git.EXE" as "git"
 2021-01-11T10:25:54.942Z DEBUG topgrade::utils  > Cannot find "doas"
 2021-01-11T10:25:54.970Z DEBUG topgrade::utils  > Detected "C:\\ProgramData\\chocolatey\\lib\\gsudo\\bin\\sudo.EXE" as "sudo"
 2021-01-11T10:25:54.997Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2021-01-11T10:25:55.006Z DEBUG topgrade::utils  > Detected "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" as "powershell"
 2021-01-11T10:25:55.281Z TRACE topgrade::executor > Output of "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" "-NoProfile" "-Command" "Split-Path $profile": Output { status: ExitStatus(ExitStatus(0)), stdout: "\\Documents\\WindowsPowerShell\r\n", stderr: "" }
 2021-01-11T10:25:55.281Z DEBUG topgrade::utils    > Path "\\Documents\\WindowsPowerShell" exists
 2021-01-11T10:25:55.282Z DEBUG topgrade::utils    > Path "\\.emacs.d" doesn't exist
 2021-01-11T10:25:55.282Z DEBUG topgrade::utils    > Path "\\AppData\\Roaming\\.emacs.d" doesn't exist
 2021-01-11T10:25:55.283Z DEBUG topgrade::steps::git > Checking if \\?\\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState is a git repository
 2021-01-11T10:25:55.283Z DEBUG topgrade::steps::git > Transformed path to \AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState
 2021-01-11T10:25:55.318Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(128)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2021-01-11T10:25:55.319Z DEBUG topgrade::steps::git > Checking if \\?\\Documents\WindowsPowerShell is a git repository
 2021-01-11T10:25:55.319Z DEBUG topgrade::steps::git > Transformed path to \WindowsPowerShell
 2021-01-11T10:25:55.352Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(128)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2021-01-11T10:25:55.353Z DEBUG topgrade::runner     > Step ".NET"
 2021-01-11T10:25:55.371Z DEBUG topgrade::utils      > Detected "C:\\Program Files\\dotnet\\dotnet.EXE" as "dotnet"

―― 11:25:55 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
.NET: SKIPPED: dotnet failed with exit code ExitStatus(ExitStatus(2147516561))
 2021-01-11T10:25:55.401Z DEBUG topgrade::terminal   > Desktop notification: Topgrade finished sucessfully

MSYS ~/Development/topgrade (dotnet-fix)
```

It looks good to me. Thanks a lot for the quick fix!

**Pull request merged**
