### PR TITLE
Launch bash to find topgrade in WSL (fix #612)

### LINKED ISSUE #612: Topgrade doesn't detect topgrade inside WSL via Nix
**What did you expect to happen?**
Running topgrade should also detect and run topgrade inside WSL.

**What actually happened?**
The WSL step is skipped.

**Additional details:**
- Which operating system or Linux distribution are you using? Windows 10, Ubuntu 20.04 LTS inside WSL
- How did you install Topgrade? Installed with scoop in Windows, installed with nix in WSL

<details><pre>
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Alex> wsl which topgrade
PS C:\Users\Alex> wsl bash -l which topgrade
/home/ajgrf/.nix-profile/bin/topgrade
PS C:\Users\Alex> topgrade -v
 2021-02-01T16:54:06.418Z DEBUG topgrade::config > Configuration at C:\Users\Alex\AppData\Roaming\topgrade.toml
 2021-02-01T16:54:06.418Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None }), linux: Some(Linux { yay_arguments: None, trizen_arguments: None, dnf_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None }), vagrant: None }
 2021-02-01T16:54:06.419Z DEBUG topgrade         > Version: 6.3.2
 2021-02-01T16:54:06.419Z DEBUG topgrade         > OS: x86_64-pc-windows-msvc
 2021-02-01T16:54:06.419Z DEBUG topgrade         > Args { inner: ["C:\\Users\\Alex\\scoop\\apps\\topgrade\\current\\topgrade.exe", "-v"] }
 2021-02-01T16:54:06.419Z DEBUG topgrade         > Binary path: Ok("C:\\Users\\Alex\\scoop\\apps\\topgrade\\current\\topgrade.exe")
 2021-02-01T16:54:06.419Z DEBUG topgrade         > Self Update: true
 2021-02-01T16:54:06.420Z DEBUG topgrade::utils  > Detected "C:\\Users\\Alex\\scoop\\shims\\git.EXE" as "git"
 2021-02-01T16:54:06.422Z DEBUG topgrade::utils  > Cannot find "doas"
 2021-02-01T16:54:06.424Z DEBUG topgrade::utils  > Detected "C:\\Users\\Alex\\scoop\\shims\\sudo.CMD" as "sudo"

―― 10:54:06 - Self update ―――――――――――――――――――――――――――――――――――――――――――――――――――――
Topgrade is up-to-date
 2021-02-01T16:54:06.655Z DEBUG topgrade::utils  > Cannot find "pwsh"
 2021-02-01T16:54:06.655Z DEBUG topgrade::utils  > Detected "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" as "powershell"
 2021-02-01T16:54:06.802Z TRACE topgrade::executor > Output of "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" "-NoProfile" "-Command" "Split-Path $profile": Output { status: ExitStatus(ExitStatus(0)), stdout: "C:\\Users\\Alex\\Documents\\WindowsPowerShell\r\n", stderr: "" }
 2021-02-01T16:54:06.803Z DEBUG topgrade::utils    > Path "C:\\Users\\Alex\\Documents\\WindowsPowerShell" exists
 2021-02-01T16:54:06.803Z DEBUG topgrade::runner   > Step "WSL"
 2021-02-01T16:54:06.803Z DEBUG topgrade::utils    > Detected "C:\\Windows\\system32\\wsl.EXE" as "wsl"
 2021-02-01T16:54:06.860Z TRACE topgrade::executor > Output of "C:\\Windows\\system32\\wsl.EXE" "which" "topgrade": Output { status: ExitStatus(ExitStatus(1)), stdout: "", stderr: "" }
 2021-02-01T16:54:06.860Z DEBUG topgrade::runner   > Step "Chocolatey"
 2021-02-01T16:54:06.861Z DEBUG topgrade::utils    > Detected "C:\\ProgramData\\chocolatey\\bin\\choco.EXE" as "choco"

―― 10:54:06 - Chocolatey ――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2021-02-01T16:54:06.866Z DEBUG topgrade::executor > Running "C:\\Users\\Alex\\scoop\\shims\\sudo.CMD" "choco" "upgrade" "all"
Chocolatey v0.10.15
Upgrading the following packages:
all
By upgrading you accept licenses for the packages.
autohotkey.portable v1.1.33.02 is the latest version available based on your source(s).
brave v1.19.88 is the latest version available based on your source(s).
chocolatey v0.10.15 is the latest version available based on your source(s).
chocolatey-core.extension v1.3.5.1 is the latest version available based on your source(s).
chocolatey-dotnetfx.extension v1.0.1 is the latest version available based on your source(s).
chocolatey-misc-helpers.extension v0.0.4 is the latest version available based on your source(s).
chocolatey-windowsupdate.extension v1.0.4 is the latest version available based on your source(s).
chocolateygui v0.17.3 is the latest version available based on your source(s).
DotNet4.5.2 v4.5.2.20140902 is the latest version available based on your source(s).
dotnetfx v4.8.0.20190930 is the latest version available based on your source(s).
egnyte-connect v3.8.3.29 is the latest version available based on your source(s).
element-desktop v1.7.18 is the latest version available based on your source(s).
epicgameslauncher v1.1.298.0 is the latest version available based on your source(s).
Firefox v85.0 is the latest version available based on your source(s).
goggalaxy v2.0.35.19 is the latest version available based on your source(s).
hunspell.portable v1.7.0 is the latest version available based on your source(s).
KB2919355 v1.0.20160915 is the latest version available based on your source(s).
KB2919442 v1.0.20160915 is the latest version available based on your source(s).
KB2999226 v1.0.20181019 is the latest version available based on your source(s).
KB3033929 v1.0.5 is the latest version available based on your source(s).
KB3035131 v1.0.3 is the latest version available based on your source(s).
origin v10.5.91.46291 is the latest version available based on your source(s).
PSWindowsUpdate v2.2.0.2 is the latest version available based on your source(s).
spotify v1.1.51.382 is the latest version available based on your source(s).
steam v3.0.1.20190215 is the latest version available based on your source(s).
vcredist140 v14.28.29325.2 is the latest version available based on your source(s).
vcredist2010 v10.0.40219.2 is the latest version available based on your source(s).
vcredist2013 v12.0.40660.20180427 is the latest version available based on your source(s).
vcredist2015 v14.0.24215.20170201 is the latest version available based on your source(s).
veracrypt v1.24.20200814 is the latest version available based on your source(s).
vlc v3.0.12 is the latest version available based on your source(s).

Chocolatey upgraded 0/31 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Enjoy using Chocolatey? Explore more amazing features to take your
experience to the next level at
 https://chocolatey.org/compare
 2021-02-01T16:54:13.047Z DEBUG topgrade::runner   > Step "Scoop"
 2021-02-01T16:54:13.048Z DEBUG topgrade::utils    > Detected "C:\\Users\\Alex\\scoop\\shims\\scoop.CMD" as "scoop"

―― 10:54:13 - Scoop ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2021-02-01T16:54:13.053Z DEBUG topgrade::executor > Running "C:\\Users\\Alex\\scoop\\shims\\scoop.CMD" "update"
Updating Scoop...
Updating 'ajgrf' bucket...
Updating 'clojure' bucket...
Updating 'extras' bucket...
Updating 'games' bucket...
Updating 'java' bucket...
Updating 'kopia' bucket...
Updating 'main' bucket...
Updating 'nonportable' bucket...
Scoop was updated successfully!
 2021-02-01T16:54:18.429Z DEBUG topgrade::executor > Running "C:\\Users\\Alex\\scoop\\shims\\scoop.CMD" "update" "*"
Latest versions for all apps are installed! For more information try 'scoop status'
 2021-02-01T16:54:19.492Z DEBUG topgrade::utils    > Path "C:\\Users\\Alex\\.emacs.d" doesn't exist
 2021-02-01T16:54:19.492Z DEBUG topgrade::utils    > Path "C:\\Users\\Alex\\AppData\\Roaming\\.emacs.d" doesn't exist
 2021-02-01T16:54:19.493Z DEBUG topgrade::steps::git > C:\Users\Alex\.doom.d does not exists
 2021-02-01T16:54:19.493Z DEBUG topgrade::steps::git > C:\Users\Alex\.vim does not exists
 2021-02-01T16:54:19.494Z DEBUG topgrade::steps::git > C:\Users\Alex\.config/nvim does not exists
 2021-02-01T16:54:19.495Z DEBUG topgrade::steps::git > C:\Users\Alex\AppData\Local\Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState does not exists
 2021-02-01T16:54:19.495Z DEBUG topgrade::steps::git > Checking if \\?\C:\Users\Alex\Documents\WindowsPowerShell is a git repository
 2021-02-01T16:54:19.496Z DEBUG topgrade::steps::git > Transformed path to C:\Users\Alex\Documents\WindowsPowerShell
 2021-02-01T16:54:19.542Z TRACE topgrade::executor   > Output of "C:\\Users\\Alex\\scoop\\shims\\git.EXE" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(128)), stdout: "", stderr: "fatal: not a git repository (or any of the parent directories): .git\n" }
 2021-02-01T16:54:19.542Z DEBUG topgrade::runner     > Step "Git repositories"
 2021-02-01T16:54:19.544Z DEBUG topgrade::runner     > Step "Powershell Modules Update"

―― 10:54:19 - Powershell Modules Update ―――――――――――――――――――――――――――――――――――――――
Updating modules...
 2021-02-01T16:54:19.549Z DEBUG topgrade::executor   > Running "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" "-NoProfile" "-Command" "Update-Module -Verbose"
 2021-02-01T16:54:21.553Z DEBUG topgrade::runner     > Step "apm"
 2021-02-01T16:54:21.555Z DEBUG topgrade::runner     > Step "rustup"
 2021-02-01T16:54:21.557Z DEBUG topgrade::runner     > Step ".NET"
 2021-02-01T16:54:21.559Z DEBUG topgrade::runner     > Step "choosenim"
 2021-02-01T16:54:21.561Z DEBUG topgrade::runner     > Step "cargo"
 2021-02-01T16:54:21.563Z DEBUG topgrade::runner     > Step "Flutter"
 2021-02-01T16:54:21.565Z DEBUG topgrade::runner     > Step "Go"
 2021-02-01T16:54:21.567Z DEBUG topgrade::runner     > Step "Emacs"
 2021-02-01T16:54:21.569Z DEBUG topgrade::runner     > Step "opam"
 2021-02-01T16:54:21.570Z DEBUG topgrade::runner     > Step "vcpkg"
 2021-02-01T16:54:21.572Z DEBUG topgrade::runner     > Step "pipx"
 2021-02-01T16:54:21.574Z DEBUG topgrade::runner     > Step "stack"
 2021-02-01T16:54:21.576Z DEBUG topgrade::runner     > Step "tlmgr"
 2021-02-01T16:54:21.579Z DEBUG topgrade::runner     > Step "myrepos"
 2021-02-01T16:54:21.581Z DEBUG topgrade::runner     > Step "jetpack"
 2021-02-01T16:54:21.582Z DEBUG topgrade::runner     > Step "vim"
 2021-02-01T16:54:21.584Z DEBUG topgrade::runner     > Step "Neovim"
 2021-02-01T16:54:21.586Z DEBUG topgrade::runner     > Step "voom"
 2021-02-01T16:54:21.588Z DEBUG topgrade::runner     > Step "npm"
 2021-02-01T16:54:21.589Z DEBUG topgrade::runner     > Step "yarn"
 2021-02-01T16:54:21.591Z DEBUG topgrade::runner     > Step "deno"
 2021-02-01T16:54:21.593Z DEBUG topgrade::runner     > Step "composer"
 2021-02-01T16:54:21.595Z DEBUG topgrade::runner     > Step "krew"
 2021-02-01T16:54:21.597Z DEBUG topgrade::runner     > Step "gem"
 2021-02-01T16:54:21.599Z DEBUG topgrade::runner     > Step "sheldon"
 2021-02-01T16:54:21.601Z DEBUG topgrade::runner     > Step "rtcl"
 2021-02-01T16:54:21.602Z DEBUG topgrade::runner     > Step "gcloud"
 2021-02-01T16:54:21.604Z DEBUG topgrade::runner     > Step "Windows update"
 2021-02-01T16:54:21.605Z DEBUG topgrade::utils      > Detected "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" as "powershell"
 2021-02-01T16:54:21.834Z TRACE topgrade::executor   > Output of "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" "-NoProfile" "-Command" "Get-Module -ListAvailable PSWindowsUpdate": Output { status: ExitStatus(ExitStatus(0)), stdout: "\r\n\r\n    Directory: C:\\Program Files\\WindowsPowerShell\\Modules\r\n\r\n\r\nModuleType Version    Name                                ExportedCommands    \r\n---------- -------    ----                                ----------------    \r\nBinary     2.2.0.2    PSWindowsUpdate                     {Add-WUServiceMan...\r\n\r\n\r\n", stderr: "" }

―― 10:54:21 - Windows Update ――――――――――――――――――――――――――――――――――――――――――――――――――
 2021-02-01T16:54:21.839Z DEBUG topgrade::executor   > Running "C:\\Users\\Alex\\scoop\\shims\\sudo.CMD" "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.EXE" "-NoProfile" "-Command" "Import-Module PSWindowsUpdate; Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -Verbose"
VERBOSE: ALEXAORUSB550I (2/1/2021 10:54:24 AM): Connecting to Microsoft Update
 server. Please wait...
VERBOSE: Found [0] Updates in pre search criteria

―― 10:54:35 - Summary ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
WSL: SKIPPED: Could not find Topgrade installed in WSL
Chocolatey: OK
Scoop: OK
Git repositories: SKIPPED: No repositories to pull
Powershell Modules Update: OK
apm: SKIPPED: Cannot find "apm" in PATH
rustup: SKIPPED: Cannot find "rustup" in PATH
.NET: SKIPPED: Cannot find "dotnet" in PATH
choosenim: SKIPPED: Cannot find "choosenim" in PATH
cargo: SKIPPED: Cannot find "cargo-install-update" in PATH
Flutter: SKIPPED: Cannot find "flutter" in PATH
Go: SKIPPED: Cannot find "go" in PATH
Emacs: SKIPPED: Cannot find "emacs" in PATH
opam: SKIPPED: Cannot find "opam" in PATH
vcpkg: SKIPPED: Cannot find "vcpkg" in PATH
pipx: SKIPPED: Cannot find "pipx" in PATH
stack: SKIPPED: Cannot find "stack" in PATH
tlmgr: SKIPPED: Cannot find "tlmgr" in PATH
myrepos: SKIPPED: Cannot find "mr" in PATH
jetpack: SKIPPED: Cannot find "jetpack" in PATH
vim: SKIPPED: Cannot find "vim" in PATH
Neovim: SKIPPED: Cannot find "nvim" in PATH
voom: SKIPPED: Cannot find "voom" in PATH
npm: SKIPPED: Cannot find "npm" in PATH
yarn: SKIPPED: Cannot find "yarn" in PATH
deno: SKIPPED: Cannot find "deno" in PATH
composer: SKIPPED: Cannot find "composer" in PATH
krew: SKIPPED: Cannot find "kubectl-krew" in PATH
gem: SKIPPED: Cannot find "gem" in PATH
sheldon: SKIPPED: Cannot find "sheldon" in PATH
rtcl: SKIPPED: Cannot find "rupdate" in PATH
gcloud: SKIPPED: Cannot find "gcloud" in PATH
Windows update: OK
 2021-02-01T16:54:35.452Z DEBUG topgrade::terminal   > Desktop notification: Topgrade finished sucessfully
PS C:\Users\Alex>
</pre></details>

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@ajgrf c can you test if this branch fixes your issue?

**Comment by ajgrf** [comment]
Thanks for your help, although it doesn't work. Using nix, `topgrade` is added to `$PATH` from my shell profile, but `bash -c` skips reading the profile.

I found [this commit](https://github.com/r-darwish/topgrade/commit/db1dea9beaa2f52f8dcc18a7eaf9bf7a5bd906f7) from last August, which confuses me a little bit. It seems topgrade used to read the profile, but that caused some other problem?

**Comment by r-darwish** [comment]
Which file defines your PATH? Is it bashrc or profile?

**Comment by ajgrf** [comment]
Both? I put it in [profile](https://github.com/ajgrf/dotfiles/blob/master/.profile), but I also put a check in [bashrc](https://github.com/ajgrf/dotfiles/blob/master/.bashrc) that reads `.profile` if it hasn't been read yet.

**Comment by r-darwish** [comment]
I'll revert db1dea9beaa2f52f8dcc18a7eaf9bf7a5bd906f7 and see if it causes issues

**Pull request closed without merging**
