### PR TITLE
Turn off colors in git when pulling (fix #538)

### LINKED ISSUE #538: topgrade on windows: git output contains / breaks ANSI control sequences
This is similar to #115, but occurs after the change intended to fix it.  My suggested fix:  `git -c color.ui false ...`

That should disable all color output from git, overriding the user configuration and repo configuration, which should avoid triggering whatever the problem is.

The `-c {setting}={value}` part needs to come *before* the command.  This makes it impossible to add this to the `arguments` field in `[git]`, since that is added after the command.  Demonstration:

```shell
PS C:\Users\danie> git -c 'color.ui=false' pull
Current branch master is up to date.
PS C:\Users\danie> git pull -c 'color.ui=false'
error: unknown switch `c'
usage: git pull [<options>] [<repository> [<refspec>...]]
```

**What actually happened?**
```shell
―― 12:36:24 - Git repositories ―――――――――――――――――――――――――――――――――――――――――――――――――
Pulling C:/Users/danie
←[32m←[1mUp-to-date←[0m C:/Users/danie
←[1m
―― 12:36:27 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――←[0m
Git repositories: ←[32m←[1mOK←[0m
```

**Additional details:**
- OS: Windows 10 2004 / 19041.508 – most recent major update
- topgrade: manually downloaded binary build, uses self-update
- Windows Terminal Version: 1.3.2651.0

<details><pre>
PS C:\Users\danie> topgrade -v --only git_repos
 2020-10-05T16:39:54.627Z DEBUG topgrade::config > Configuration at C:\Users\danie\AppData\Roaming\topgrade.toml
 2020-10-05T16:39:54.627Z DEBUG topgrade::config > Path ~/ expanded to C:\Users\danie/
 2020-10-05T16:39:54.627Z DEBUG topgrade::config > Path ~/share/hunspell expanded to C:\Users\danie/share/hunspell
 2020-10-05T16:39:54.627Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, post_commands: None, commands: Some({"conform": "conform"}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: Some(true), notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None, brew: None, linux: None, git: Some(Git { max_concurrency: Some(5), arguments: Some("--rebase --autostash"), repos: Some(["C:\\Users\\danie/", "C:\\Users\\danie/share/hunspell"]), pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None }), vagrant: None }
 2020-10-05T16:39:54.628Z DEBUG topgrade         > Version: 5.8.1
 2020-10-05T16:39:54.628Z DEBUG topgrade         > OS: x86_64-pc-windows-msvc
 2020-10-05T16:39:54.628Z DEBUG topgrade         > Args { inner: ["c:\\users\\danie\\bin\\windows\\topgrade.exe", "-v", "--only", "git_repos"] }
 2020-10-05T16:39:54.628Z DEBUG topgrade         > Binary path: Ok("c:\\users\\danie\\bin\\windows\\topgrade.exe")
 2020-10-05T16:39:54.628Z DEBUG topgrade         > Self Update: true
 2020-10-05T16:39:54.641Z DEBUG topgrade::utils  > Detected "C:\\Program Files\\Git\\cmd\\git.EXE" as "git"
 2020-10-05T16:39:54.655Z DEBUG topgrade::utils  > Detected "C:\\Users\\danie\\scoop\\shims\\sudo.EXE" as "sudo"

―― 12:39:54 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Topgrade is up-to-date
 2020-10-05T16:39:54.794Z DEBUG topgrade::utils  > Detected "C:\\Program Files\\PowerShell\\7\\pwsh.EXE" as "pwsh"
 2020-10-05T16:39:57.208Z TRACE topgrade::executor > Output of "C:\\Program Files\\PowerShell\\7\\pwsh.EXE" "-Command" "echo $profile": Output { status: ExitStatus(ExitStatus(0)), stdout: "C:\\Users\\danie\\Documents\\PowerShell\\Microsoft.PowerShell_profile.ps1\r\n", stderr: "" }
 2020-10-05T16:39:57.209Z DEBUG topgrade::utils    > Path "C:\\Users\\danie\\.emacs.d" exists
 2020-10-05T16:39:57.209Z DEBUG topgrade::utils    > Path "C:\\Users\\danie\\.emacs.d\\bin/doom.cmd" doesn't exist
 2020-10-05T16:39:57.209Z DEBUG topgrade::steps::git > Checking if \\?\C:\Users\danie\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState is a git repository
 2020-10-05T16:39:57.209Z DEBUG topgrade::steps::git > Transformed path to C:\Users\danie\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState
 2020-10-05T16:39:57.251Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(0)), stdout: "C:/Users/danie\n", stderr: "" }
 2020-10-05T16:39:57.252Z DEBUG topgrade::steps::git > Checking if \\?\C:\Users\danie is a git repository
 2020-10-05T16:39:57.252Z DEBUG topgrade::steps::git > Transformed path to C:\Users\danie
 2020-10-05T16:39:57.286Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(0)), stdout: "C:/Users/danie\n", stderr: "" }
 2020-10-05T16:39:57.287Z DEBUG topgrade::runner     > Step "Git repositories"

―― 12:39:57 - Git repositories ―――――――――――――――――――――――――――――――――――――――――――――――――
 2020-10-05T16:39:57.331Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "remote" "show": Output { status: ExitStatus(ExitStatus(0)), stdout: "origin\n", stderr: "" }
 2020-10-05T16:39:57.368Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "HEAD": Output { status: ExitStatus(ExitStatus(0)), stdout: "2f2f63a53e72a7e0debdf44a6b875f6485b24ac9\n", stderr: "" }
Pulling C:/Users/danie
 2020-10-05T16:40:01.273Z ←[0m←[35mTRACE←[0m ←[0m←[1mtopgrade::executor  ←[0m > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "HEAD": Output { status: ExitStatus(ExitStatus(0)), stdout: "2f2f63a53e72a7e0debdf44a6b875f6485b24ac9\n", stderr: "" }
←[32m←[1mUp-to-date←[0m C:/Users/danie
←[1m
―― 12:40:01 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――←[0m
Git repositories: ←[32m←[1mOK←[0m
</pre></details>

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@slippycheeze can you test this out?

**Comment by slippycheeze** [comment]
Huh.  No.  I'm afraid it doesn't work:
```shell
Pulling C:/Users/danie
 2020-10-06T19:07:47.121Z ←[0m←[35mTRACE←[0m ←[0m←[1mtopgrade::executor  ←[0m > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "HEAD": Output { status: ExitStatus(ExitStatus(0)), stdout: "2f2f63a53e72a7e0debdf44a6b875f6485b24ac9\n", stderr: "" }
←[32m←[1mUp-to-date←[0m C:/Users/danie
←[1m
―― 15:07:47 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――←[0m
Git repositories: ←[32m←[1mOK←[0m
```

**Comment by r-darwish** [comment]
I made another commit which adds the `-c` to additional commands such as `rev-parse`. Can you check again?

**Comment by slippycheeze** [comment]
Dang, no.  Same problem.  Since I shouldn't depend on you round-tripping this all the time I did some digging.  (plus, a chance to learn a tiny bit of rust.)

The problem occurs if the `git submodule update` command is executed at all.  It doesn't need to pass to `check_output` for it to break the console.  I'm not certain why yet, but figured I'd share that.  Simple commenting out the code there, or turning it into `git status` fixes the issue.

I'll investigate a little further why this is happening...

**Comment by slippycheeze** [comment]
...and I don't know what the root cause is, but I found out how to make it go away.  For me, that is sufficient.  For you, I don't know, but it at least fixes `git version 2.28.0.windows.1` for me.

```patch
diff --git a/src/steps/git.rs b/src/steps/git.rs
index 7385efb..b9391a9 100644
--- a/src/steps/git.rs
+++ b/src/steps/git.rs
@@ -1,7 +1,7 @@
 use std::collections::HashSet;
 use std::io;
 use std::path::{Path, PathBuf};
-use std::process::{Command, Output};
+use std::process::{Command, Output, Stdio};
 
 use anyhow::Result;
 use console::style;
@@ -61,6 +61,7 @@ async fn pull_repository(repo: String, git: &PathBuf, ctx: &ExecutionContext<'_>
     let submodule_output = AsyncCommand::new(git)
         .args(&["-c", "color.ui=false", "submodule", "update", "--recursive"])
         .current_dir(&repo)
+        .stdin(Stdio::null())
         .output()
         .await?;
     let result = check_output(pull_output).and_then(|_| check_output(submodule_output));
```

**Comment by slippycheeze** [comment]
OK, sent PR #543 that applies my suggested change to all the subcommand invocations.  It also includes a pile of explanatory text in the commit description, since the path is definitely not obvious, and hopefully that'll help the next maintainer.

**Pull request closed without merging**
