### PR TITLE
fix: pacstall should run without yay arguments

### PR DESCRIPTION
**Pull request by Zahrun**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@Zahrun please fix the formatting

**Review by r-darwish — CHANGES_REQUESTED** [review]
Please fix the formatting

**Comment by Zahrun** [comment]
> Please fix the formatting

Sorry, I only removed two lines.
What format is wrong?

**Comment by r-darwish** [comment]
> > Please fix the formatting
> 
> Sorry, I only removed two lines. What format is wrong?

See [this link](https://github.com/r-darwish/topgrade/runs/4715546374?check_suite_focus=true). You can run `cargo fmt` and it should probably fix it.

**Comment by Zahrun** [comment]
> > > Please fix the formatting
> > 
> > 
> > Sorry, I only removed two lines. What format is wrong?
> 
> See [this link](https://github.com/r-darwish/topgrade/runs/4715546374?check_suite_focus=true). You can run `cargo fmt` and it should probably fix it.

Right, sorry. I had run `cargo fmt` only after committing.

**Pull request merged**
