### PR TITLE
Don't require sudo for ostree (fix #479)

### LINKED ISSUE #479: Remove need for sudo in rpm-ostree
**What did you expect to happen?**
rpm-ostree upgrade should happen without sudo since rpm-ostree works without sudo, at least for sudoers.

**What actually happened?**
It asks for root password.

**Additional details:**
- Which operating system or Linux distribution are you using? Fedora Silverblue
- How did you install Topgrade? Cargo

### PR DESCRIPTION
**Pull request by r-darwish**
## Standards checklist:

- [ ] The PR title is descriptive.
- [ ] The code compiles
- [ ] The code passes rustfmt
- [ ] The code passes clippy
- [ ] The code passes tests
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
@minioin can you please test this change?

**Comment by minioin** [comment]
You've missed the command _update_ for rpm-ostree. I fixed the issue on my copy of code and ran all the tests. It works.
- [x] The PR title is descriptive.
- [x] The code compiles
- [x] The code passes rustfmt
- [x] The code passes clippy
- [x] The code passes tests
- [x] Optional: I have tested the code myself
   - [x] I also tested that Topgrade skips the step where needed

**Comment by r-darwish** [comment]
Fixed. Can you please check again?

**Comment by minioin** [comment]
Already checked earlier with the same change. It should work.

**Pull request merged**
