### PR TITLE
Pull zsh themes (fix #471)

### LINKED ISSUE #471: Update oh-my-zsh custom themes
**I want to suggest a new step**
***Which tool is this about? Where is its repository?***
Oh my zsh, can have custom plugins and custom themes. Currently only plugin are pulled during the step. We can pull themes too.
***Which operating systems are supported by this tool?***
Linux, Mac and Windows
***What should Topgrade do to figure out if the tool needs to be invoked?***
Check every repository in $ZSH_CUSTOM/themes
***Which exact commands should Topgrade run?***
Like a git repository

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by r-darwish** [comment]
@EmilienMottet can you please test this change?

**Comment by EmilienMottet** [comment]
@r-darwish 
Thanks you for your help but I have an error 

```
―― 10:43:47 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-07-15T08:43:47.308Z TRACE topgrade::executor         > Output of "zsh" "-c" "echo -n $ZSH_CUSTOM": Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "" }
 2020-07-15T08:43:47.308Z DEBUG topgrade::steps::zsh       > oh-my-zsh custom dir: 
 2020-07-15T08:43:47.309Z DEBUG topgrade::terminal         > Desktop notification: oh-my-zsh failed
```

No problem with the previous commit `e8851af9`

But this problem should be independent of your change
I will inspect on my side.

**Comment by r-darwish** [comment]
I think a9e529eb795cc2e443d1f5b1ee79966591365f3c is the commit that broke you. Can you check? If so, I'll make a fix in this commit as well.

**Comment by EmilienMottet** [comment]
Yes, I revert `a9e529e` and it's ok for me

**Comment by r-darwish** [comment]
@EmilienMottet  Can you please check if my latest commit to this branch fixes the issue?

**Comment by EmilienMottet** [comment]
With your latest commit, fail too

```
―― 09:49:19 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-07-21T07:49:19.098Z TRACE topgrade::executor         > Output of "zsh" "-c" "echo -n $ZSH_CUSTOM": Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "" }
 2020-07-21T07:49:19.099Z DEBUG topgrade::steps::zsh       > oh-my-zsh custom dir: 
 2020-07-21T07:49:19.099Z DEBUG topgrade::terminal         > Desktop notification: oh-my-zsh failed
```

**Comment by r-darwish** [comment]
I pushed another fix. Can you try once more?

**Comment by EmilienMottet** [comment]
No crash, but doesn't pull git directory in `$ZSH_CUSTOM/plugins` and `$ZSH_CUSTOM/plugins`

```
―― 15:37:20 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-07-21T13:37:20.176Z TRACE topgrade::executor   > Output of "zsh" "-c" "test $ZSH_CUSTOM && echo -n $ZSH_CUSTOM": Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "" }
 2020-07-21T13:37:20.176Z DEBUG topgrade::steps::zsh > Running zsh returned exit code: 1: . Using default path: /home/emottet/.oh-my-zsh/custom
 2020-07-21T13:37:20.176Z DEBUG topgrade::steps::zsh > oh-my-zsh custom dir: /home/emottet/.oh-my-zsh/custom
 2020-07-21T13:37:20.176Z DEBUG topgrade::steps::git > Checking if /home/emottet/.oh-my-zsh/custom is a git repository
 2020-07-21T13:37:20.179Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(0)), stdout: "/home/emottet/.oh-my-zsh\n", stderr: "" }
 2020-07-21T13:37:20.179Z DEBUG topgrade::steps::git > Checking if /home/emottet/.oh-my-zsh/custom/plugins is a git repository
 2020-07-21T13:37:20.181Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(0)), stdout: "/home/emottet/.oh-my-zsh\n", stderr: "" }
 2020-07-21T13:37:20.181Z DEBUG topgrade::steps::git > Checking if /home/emottet/.oh-my-zsh/custom/themes is a git repository
 2020-07-21T13:37:20.183Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(0)), stdout: "/home/emottet/.oh-my-zsh\n", stderr: "" }
 2020-07-21T13:37:20.183Z DEBUG topgrade::steps::git > /home/emottet/.oh-my-zsh/custom/example.zsh is a file. Checking /home/emottet/.oh-my-zsh/custom
 2020-07-21T13:37:20.183Z DEBUG topgrade::steps::git > Checking if /home/emottet/.oh-my-zsh/custom is a git repository
 2020-07-21T13:37:20.185Z TRACE topgrade::executor   > Output of "/usr/bin/git" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(0)), stdout: "/home/emottet/.oh-my-zsh\n", stderr: "" }
 2020-07-21T13:37:20.185Z DEBUG topgrade::executor   > Running "sh" "/home/emottet/.oh-my-zsh/tools/upgrade.sh"
Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch              master     -> FETCH_HEAD
Current branch master is up to date.
         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
                        /____/                       
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on Twitter: https://twitter.com/ohmyzsh
Want to get involved in the community? Join our Discord: https://discord.gg/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh

```

**Comment by EmilienMottet** [comment]
I can suggest you this fix 

https://github.com/r-darwish/topgrade/compare/zsh-themes...EmilienMottet:zsh-themes

**Comment by r-darwish** [comment]
Thanks. I applied your suggestion. Does it work now?

**Comment by EmilienMottet** [comment]
It's work well, thank you !

**Pull request merged**
