### PR TITLE
Upgrade arg parsing to clap v3

### PR DESCRIPTION
**Pull request by tranzystorek-io**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [x] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [ ] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by r-darwish** [comment]
Topgrade is checked against 1.51 so can compile with Ubuntu 20.04's version of Rust, so we cannot use any feature that required a more recent version.

**Comment by MCOfficer** [comment]
> Topgrade is checked against 1.51 so can compile with Ubuntu 20.04's version of Rust, so we cannot use any feature that required a more recent version.

Focal currently has 1.53: https://packages.ubuntu.com/focal/rustc

**Comment by tranzystorek-io** [comment]
Should topgrade be rounded to rustc versions stored in distro package repositories? Those are usually maintained for the use of the packages of those distros, while end users should use rustup?

**Comment by r-darwish** [comment]
I bumped the version of Rust in the CI to 1.53. Please rebase/merge your  branch

**Comment by r-darwish** [comment]
It seems that there's another feature which is unstable in 1.53

**Comment by tranzystorek-io** [comment]
> It seems that there's another feature which is unstable in 1.53

This one needs 1.54

**Comment by r-darwish** [comment]
I bumped it to 1.53 because this is the version that comes with Ubuntu 20.04. Not everyone wants to use Rustup to get Rust. I'll bump it further if the version of Rust in 20.04 will keep updating.

**Comment by tranzystorek-io** [comment]
Sounds reasonable

**Comment by r-darwish** [comment]
Let's reopen this once it does.

**Comment by tranzystorek-io** [comment]
Looks like Rust 1.57 has been backported to 20.04, seems we could reopen this 😄

**Pull request closed without merging**
