### PR TITLE
Upgrade arg parsing to clap v3, take two

### PR DESCRIPTION
**Pull request by tranzystorek-io**
## Standards checklist:

- [x] The PR title is descriptive.
- [x] The code compiles (`cargo build`)
- [x] The code passes rustfmt (`cargo fmt`)
- [ ] The code passes clippy (`cargo clippy`)
- [x] The code passes tests (`cargo test`)
- [x] *Optional:* I have tested the code myself
    - [ ] I also tested that Topgrade skips the step where needed

If you developed a feature or a bug fix for someone else and you do not have the
means to test it, please tag this person here.

### CODE REVIEW

**Comment by MCOfficer** [comment]
The CI is still running on 1.53.

**Comment by tranzystorek-io** [comment]
Seems clippy has become a bit less nice 😅

**Comment by r-darwish** [comment]
@tranzystorek-io can you please rebase/merge your PR so you include https://github.com/r-darwish/topgrade/commit/b1e04eb5cbb56e9c29d5c973645b0b8f337faadc ?

**Comment by tranzystorek-io** [comment]
@r-darwish I rebased it preemptively before submitting the PR, it already includes that commit, but it seems like clippy has more complaints in Rust 1.57

**Review by r-darwish — APPROVED** [review]

**Pull request merged**
